NiceCompetency.destroy_all

NiceCompetency.create(name: "Access Controls", description: "This Competency Area describes a learner's capabilities to define, manage, and monitor the roles and secure access privileges of who is authorized to access protected data and resources and understand the impact of different types of access controls.", competency_code: "NF-COM-001")
NiceCompetency.create(name: "Artificial Intelligence (AI) Security", description: "This Competency Area describes a learner's capability to understand Artificial Intelligence (AI) systems and to use them in a secure manner that maximizes AI's benefits while minimizing potential negative risks.", competency_code: "NF-COM-002")
NiceCompetency.create(name: "Asset Management", description: "This Competency Area describes a learner's capabilities to conduct and maintain an accurate inventory of all digital assets, to include identifying, developing, operating, maintaining, upgrading, and disposing of assets.", competency_code: "NF-COM-003")
NiceCompetency.create(name: "Cloud Security", description: "This Competency Area describes a learner's capabilities to protect cloud data, applications, and infrastructure from internal and external threats.", competency_code: "NF-COM-004")
NiceCompetency.create(name: "Communications Security", description: "This Competency Area describes a learner's capabilities to secure the transmissions, broadcasting, switching, control, and operation of communications and related network infrastructures.", competency_code: "NF-COM-005")
NiceCompetency.create(name: "Cryptography", description: "This Competency Area describes a learner's capabilities to transform data using cryptographic processes to ensure it can only be read by the person who is authorized to access it.", competency_code: "NF-COM-006")
NiceCompetency.create(name: "Cyber Resiliency", description: "This Competency Area describes a learner's capability related to architecting, designing, developing, implementing, and maintaining the trustworthiness of systems that use or are enabled by cyber resources in order to anticipate, withstand, recover from, and adapt to adverse conditions, stresses, attacks, or compromises.", competency_code: "NF-COM-007")
NiceCompetency.create(name: "DevSecOps", description: "This Competency Area describes a learner's capabilities to integrate security as a shared responsibility throughout the development, security, and operations (DevSecOps) life cycle of technologies.", competency_code: "NF-COM-008")
NiceCompetency.create(name: "Operating Systems (OS) Security", description: "This Competency Area describes a learner's capabilities to install, administer, troubleshoot, backup, and conduct recovery of Operating Systems (OS), including in simulated environments.", competency_code: "NF-COM-009")
NiceCompetency.create(name: "Operational Technology (OT) Security", description: "This Competency Area describes a learner's capabilities to improve and maintain the security of Operational Technology (OT) systems while addressing their unique performance, reliability, and safety requirements.", competency_code: "NF-COM-010")
NiceCompetency.create(name: "Supply Chain Security", description: "This Competency Area describes a learner's capabilities to analyze and control digital and physical risks presented by technology products or services purchased from parties outside your organization.", competency_code: "NF-COM-011")

puts "Created #{NiceCompetency.count} NICE competencies."