NiceKnowledge.destroy_all

NiceKnowledge.create(acronym: "K0001", description: "Knowledge of computer networking concepts and protocols, and network security methodologies.")
NiceKnowledge.create(acronym: "K0002", description: "Knowledge of risk management processes (e.g., methods for assessing and mitigating risk).")
NiceKnowledge.create(acronym: "K0003", description: "Knowledge of laws, regulations, policies, and ethics as they relate to cybersecurity and privacy.")
NiceKnowledge.create(acronym: "K0004", description: "Knowledge of cybersecurity and privacy principles.")
NiceKnowledge.create(acronym: "K0005", description: "Knowledge of cyber threats and vulnerabilities.")
NiceKnowledge.create(acronym: "K0006", description: "Knowledge of specific operational impacts of cybersecurity lapses.")
NiceKnowledge.create(acronym: "K0007", description: "Knowledge of authentication, authorization, and access control methods.")
NiceKnowledge.create(acronym: "K0008", description: "Knowledge of applicable business processes and operations of customer organizations.")
NiceKnowledge.create(acronym: "K0009", description: "Knowledge of application vulnerabilities.")
NiceKnowledge.create(acronym: "K0010", description: "Knowledge of communication methods, principles, and concepts that support the network infrastructure.")
NiceKnowledge.create(acronym: "K0011", description: "Knowledge of capabilities and applications of network equipment including routers, switches, bridges, servers, transmission media, and related hardware.")
NiceKnowledge.create(acronym: "K0012", description: "Knowledge of capabilities and requirements analysis.")
NiceKnowledge.create(acronym: "K0013", description: "Knowledge of cyber defense and vulnerability assessment tools and their capabilities.")
NiceKnowledge.create(acronym: "K0014", description: "Knowledge of complex data structures.")
NiceKnowledge.create(acronym: "K0015", description: "Knowledge of computer algorithms.")
NiceKnowledge.create(acronym: "K0016", description: "Knowledge of computer programming principles")
NiceKnowledge.create(acronym: "K0017", description: "Knowledge of concepts and practices of processing digital forensic data.")
NiceKnowledge.create(acronym: "K0018", description: "Knowledge of encryption algorithms")
NiceKnowledge.create(acronym: "K0019", description: "Knowledge of cryptography and cryptographic key management concepts")
NiceKnowledge.create(acronym: "K0020", description: "Knowledge of data administration and data standardization policies.")
NiceKnowledge.create(acronym: "K0021", description: "Knowledge of data backup and recovery.")
NiceKnowledge.create(acronym: "K0022", description: "Knowledge of data mining and data warehousing principles.")
NiceKnowledge.create(acronym: "K0023", description: "Knowledge of database management systems, query languages, table relationships, and views.")
NiceKnowledge.create(acronym: "K0024", description: "Knowledge of database systems.")
NiceKnowledge.create(acronym: "K0025", description: "Knowledge of digital rights management.")
NiceKnowledge.create(acronym: "K0026", description: "Knowledge of business continuity and disaster recovery continuity of operations plans.")
NiceKnowledge.create(acronym: "K0027", description: "Knowledge of organization's enterprise information security architecture.")
NiceKnowledge.create(acronym: "K0028", description: "Knowledge of organization's evaluation and validation requirements.")
NiceKnowledge.create(acronym: "K0029", description: "Knowledge of organization's Local and Wide Area Network connections.")
NiceKnowledge.create(acronym: "K0030", description: "Knowledge of electrical engineering as applied to computer architecture (e.g., circuit boards, processors, chips, and computer hardware).")
NiceKnowledge.create(acronym: "K0031", description: "Knowledge of enterprise messaging systems and associated software.")
NiceKnowledge.create(acronym: "K0032", description: "Knowledge of resiliency and redundancy.")
NiceKnowledge.create(acronym: "K0033", description: "Knowledge of host/network access control mechanisms (e.g., access control list, capabilities lists).")
NiceKnowledge.create(acronym: "K0034", description: "Knowledge of network services and protocols interactions that provide network communications.")
NiceKnowledge.create(acronym: "K0035", description: "Knowledge of installation, integration, and optimization of system components.")
NiceKnowledge.create(acronym: "K0036", description: "Knowledge of human-computer interaction principles.")
NiceKnowledge.create(acronym: "K0037", description: "Knowledge of Security Assessment and Authorization process.")
NiceKnowledge.create(acronym: "K0038", description: "Knowledge of cybersecurity and privacy principles used to manage risks related to the use, processing, storage, and transmission of information or data.")
NiceKnowledge.create(acronym: "K0039", description: "Knowledge of cybersecurity and privacy principles and methods that apply to software development.")
NiceKnowledge.create(acronym: "K0040", description: "Knowledge of vulnerability information dissemination sources (e.g., alerts, advisories, errata, and bulletins).")
NiceKnowledge.create(acronym: "K0041", description: "Knowledge of incident categories, incident responses, and timelines for responses.")
NiceKnowledge.create(acronym: "K0042", description: "Knowledge of incident response and handling methodologies.")
NiceKnowledge.create(acronym: "K0043", description: "Knowledge of industry-standard and organizationally accepted analysis principles and methods.")
NiceKnowledge.create(acronym: "K0044", description: "Knowledge of cybersecurity and privacy principles and organizational requirements (relevant to confidentiality, integrity, availability, authentication, non-repudiation).")
NiceKnowledge.create(acronym: "K0045", description: "Knowledge of information security systems engineering principles (NIST SP 800-160).")
NiceKnowledge.create(acronym: "K0046", description: "Knowledge of intrusion detection methodologies and techniques for detecting host and network-based intrusions.")
NiceKnowledge.create(acronym: "K0047", description: "Knowledge of information technology (IT) architectural concepts and frameworks.")
NiceKnowledge.create(acronym: "K0048", description: "Knowledge of Risk Management Framework (RMF) requirements.")
NiceKnowledge.create(acronym: "K0049", description: "Knowledge of information technology (IT) security principles and methods (e.g., firewalls, demilitarized zones, encryption).")
NiceKnowledge.create(acronym: "K0050", description: "Knowledge of local area and wide area networking principles and concepts including bandwidth management.")
NiceKnowledge.create(acronym: "K0051", description: "Knowledge of low-level computer languages (e.g., assembly languages).")
NiceKnowledge.create(acronym: "K0052", description: "Knowledge of mathematics (e.g. logarithms, trigonometry, linear algebra, calculus, statistics, and operational analysis).")
NiceKnowledge.create(acronym: "K0053", description: "Knowledge of measures or indicators of system performance and availability.")
NiceKnowledge.create(acronym: "K0054", description: "Knowledge of current industry methods for evaluating, implementing, and disseminating information technology (IT) security assessment, monitoring, detection, and remediation tools and procedures utilizing standards-based concepts and capabilities.")
NiceKnowledge.create(acronym: "K0055", description: "Knowledge of microprocessors.")
NiceKnowledge.create(acronym: "K0056", description: "Knowledge of network access, identity, and access management (e.g., public key infrastructure, Oauth, OpenID, SAML, SPML).")
NiceKnowledge.create(acronym: "K0057", description: "Knowledge of network hardware devices and functions.")
NiceKnowledge.create(acronym: "K0058", description: "Knowledge of network traffic analysis methods.")
NiceKnowledge.create(acronym: "K0059", description: "Knowledge of new and emerging information technology (IT) and cybersecurity technologies.")
NiceKnowledge.create(acronym: "K0060", description: "Knowledge of operating systems.")
NiceKnowledge.create(acronym: "K0061", description: "Knowledge of how traffic flows across the network (e.g., Transmission Control Protocol [TCP] and Internet Protocol [IP], Open System Interconnection Model [OSI], Information Technology Infrastructure Library, current version [ITIL]).")
NiceKnowledge.create(acronym: "K0062", description: "Knowledge of packet-level analysis.")
NiceKnowledge.create(acronym: "K0063", description: "Knowledge of parallel and distributed computing concepts.")
NiceKnowledge.create(acronym: "K0064", description: "Knowledge of performance tuning tools and techniques.")
NiceKnowledge.create(acronym: "K0065", description: "Knowledge of policy-based and risk adaptive access controls.")
NiceKnowledge.create(acronym: "K0066", description: "Knowledge of Privacy Impact Assessments.")
NiceKnowledge.create(acronym: "K0067", description: "Knowledge of process engineering concepts.")
NiceKnowledge.create(acronym: "K0068", description: "Knowledge of programming language structures and logic.")
NiceKnowledge.create(acronym: "K0069", description: "Knowledge of query languages such as SQL (structured query language).")
NiceKnowledge.create(acronym: "K0070", description: "Knowledge of system and application security threats and vulnerabilities (e.g., buffer overflow, mobile code, cross-site scripting, Procedural Language/Structured Query Language [PL/SQL] and injections, race conditions, covert channel, replay, return-oriented attacks, malicious code).")
NiceKnowledge.create(acronym: "K0071", description: "Knowledge of remote access technology concepts.")
NiceKnowledge.create(acronym: "K0072", description: "Knowledge of resource management principles and techniques.")
NiceKnowledge.create(acronym: "K0073", description: "Knowledge of secure configuration management techniques. (e.g., Security Technical Implementation Guides (STIGs), cybersecurity best practices on cisecurity.org).")
NiceKnowledge.create(acronym: "K0074", description: "Knowledge of key concepts in security management (e.g., Release Management, Patch Management).")
NiceKnowledge.create(acronym: "K0075", description: "Knowledge of security system design tools, methods, and techniques.")
NiceKnowledge.create(acronym: "K0076", description: "Knowledge of server administration and systems engineering theories, concepts, and methods.")
NiceKnowledge.create(acronym: "K0077", description: "Knowledge of server and client operating systems.")
NiceKnowledge.create(acronym: "K0078", description: "Knowledge of server diagnostic tools and fault identification techniques.")
NiceKnowledge.create(acronym: "K0079", description: "Knowledge of software debugging principles.")
NiceKnowledge.create(acronym: "K0080", description: "Knowledge of software design tools, methods, and techniques.")
NiceKnowledge.create(acronym: "K0081", description: "Knowledge of software development models (e.g., Waterfall Model, Spiral Model).")
NiceKnowledge.create(acronym: "K0082", description: "Knowledge of software engineering.")
NiceKnowledge.create(acronym: "K0083", description: "Knowledge of sources, characteristics, and uses of the organization’s data assets.")
NiceKnowledge.create(acronym: "K0084", description: "Knowledge of structured analysis principles and methods.")
NiceKnowledge.create(acronym: "K0085", description: "WITHDRAWN: Knowledge of system and application security threats and vulnerabilities. (See K0070)")
NiceKnowledge.create(acronym: "K0086", description: "Knowledge of system design tools, methods, and techniques, including automated systems analysis and design tools.")
NiceKnowledge.create(acronym: "K0087", description: "Knowledge of system software and organizational design standards, policies, and authorized approaches (e.g., International Organization for Standardization [ISO] guidelines) relating to system design.")
NiceKnowledge.create(acronym: "K0088", description: "Knowledge of systems administration concepts.")
NiceKnowledge.create(acronym: "K0089", description: "Knowledge of systems diagnostic tools and fault identification techniques.")
NiceKnowledge.create(acronym: "K0090", description: "Knowledge of system life cycle management principles, including software security and usability.")
NiceKnowledge.create(acronym: "K0091", description: "Knowledge of systems testing and evaluation methods.")
NiceKnowledge.create(acronym: "K0092", description: "Knowledge of technology integration processes.")
NiceKnowledge.create(acronym: "K0093", description: "Knowledge of telecommunications concepts (e.g., Communications channel, Systems Link Budgeting, Spectral efficiency, Multiplexing).")
NiceKnowledge.create(acronym: "K0094", description: "Knowledge of the capabilities and functionality associated with content creation technologies (e.g., wikis, social networking, content management systems, blogs).")
NiceKnowledge.create(acronym: "K0095", description: "Knowledge of the capabilities and functionality associated with various technologies for organizing and managing information (e.g., databases, bookmarking engines).")
NiceKnowledge.create(acronym: "K0096", description: "Knowledge of the capabilities and functionality of various collaborative technologies (e.g., groupware, SharePoint).")
NiceKnowledge.create(acronym: "K0097", description: "Knowledge of the characteristics of physical and virtual data storage media.")
NiceKnowledge.create(acronym: "K0098", description: "Knowledge of the cyber defense Service Provider reporting structure and processes within one’s own organization.")
NiceKnowledge.create(acronym: "K0099", description: "WITHDRAWN: Knowledge of the common networking protocols (e.g., TCP/IP), services (e.g., web, mail, Domain Name Server), and how they interact to provide network communications.")
NiceKnowledge.create(acronym: "K0100", description: "Knowledge of the enterprise information technology (IT) architecture.")
NiceKnowledge.create(acronym: "K0101", description: "Knowledge of the organization’s enterprise information technology (IT) goals and objectives.")
NiceKnowledge.create(acronym: "K0102", description: "Knowledge of the systems engineering process.")
NiceKnowledge.create(acronym: "K0103", description: "Knowledge of the type and frequency of routine hardware maintenance.")
NiceKnowledge.create(acronym: "K0104", description: "Knowledge of Virtual Private Network (VPN) security.")
NiceKnowledge.create(acronym: "K0105", description: "Knowledge of web services (e.g., service-oriented architecture, Simple Object Access Protocol, and web service description language).")
NiceKnowledge.create(acronym: "K0106", description: "Knowledge of what constitutes a network attack and a network attack’s relationship to both threats and vulnerabilities.")
NiceKnowledge.create(acronym: "K0107", description: "Knowledge of Insider Threat investigations, reporting, investigative tools and laws/regulations.")
NiceKnowledge.create(acronym: "K0108", description: "Knowledge of concepts, terminology, and operations of a wide range of communications media (computer and telephone networks, satellite, fiber, wireless).")
NiceKnowledge.create(acronym: "K0109", description: "Knowledge of physical computer components and architectures, including the functions of various components and peripherals (e.g., CPUs, Network Interface Cards, data storage).")
NiceKnowledge.create(acronym: "K0110", description: "Knowledge of adversarial tactics, techniques, and procedures.")
NiceKnowledge.create(acronym: "K0111", description: "Knowledge of network tools (e.g., ping, traceroute, nslookup)")
NiceKnowledge.create(acronym: "K0112", description: "Knowledge of defense-in-depth principles and network security architecture.")
NiceKnowledge.create(acronym: "K0113", description: "Knowledge of different types of network communication (e.g., LAN, WAN, MAN, WLAN, WWAN).")
NiceKnowledge.create(acronym: "K0114", description: "Knowledge of electronic devices (e.g., computer systems/components, access control devices, digital cameras, digital scanners, electronic organizers, hard drives, memory cards, modems, network components, networked appliances, networked home control devices, printers, removable storage devices, telephones, copiers, facsimile machines, etc.).")
NiceKnowledge.create(acronym: "K0115", description: "Knowledge that technology that can be exploited.")
NiceKnowledge.create(acronym: "K0116", description: "Knowledge of file extensions (e.g., .dll, .bat, .zip, .pcap, .gzip).")
NiceKnowledge.create(acronym: "K0117", description: "Knowledge of file system implementations (e.g., New Technology File System [NTFS], File Allocation Table [FAT], File Extension [EXT]).")
NiceKnowledge.create(acronym: "K0118", description: "Knowledge of processes for seizing and preserving digital evidence.")
NiceKnowledge.create(acronym: "K0119", description: "Knowledge of hacking methodologies.")
NiceKnowledge.create(acronym: "K0120", description: "Knowledge of how information needs and collection requirements are translated, tracked, and prioritized across the extended enterprise.")
NiceKnowledge.create(acronym: "K0121", description: "Knowledge of information security program management and project management principles and techniques.")
NiceKnowledge.create(acronym: "K0122", description: "Knowledge of investigative implications of hardware, Operating Systems, and network technologies.")
NiceKnowledge.create(acronym: "K0123", description: "Knowledge of legal governance related to admissibility (e.g. Rules of Evidence).")
NiceKnowledge.create(acronym: "K0124", description: "Knowledge of multiple cognitive domains and tools and methods applicable for learning in each domain.")
NiceKnowledge.create(acronym: "K0125", description: "Knowledge of processes for collecting, packaging, transporting, and storing electronic evidence while maintaining chain of custody.")
NiceKnowledge.create(acronym: "K0126", description: "Knowledge of Supply Chain Risk Management Practices (NIST SP 800-161)")
NiceKnowledge.create(acronym: "K0127", description: "Knowledge of the nature and function of the relevant information structure (e.g., National Information Infrastructure).")
NiceKnowledge.create(acronym: "K0128", description: "Knowledge of types and collection of persistent data.")
NiceKnowledge.create(acronym: "K0129", description: "Knowledge of command-line tools (e.g., mkdir, mv, ls, passwd, grep).")
NiceKnowledge.create(acronym: "K0130", description: "Knowledge of virtualization technologies and virtual machine development and maintenance.")
NiceKnowledge.create(acronym: "K0131", description: "Knowledge of web mail collection, searching/analyzing techniques, tools, and cookies.")
NiceKnowledge.create(acronym: "K0132", description: "Knowledge of which system files (e.g., log files, registry files, configuration files) contain relevant information and where to find those system files.")
NiceKnowledge.create(acronym: "K0133", description: "Knowledge of types of digital forensics data and how to recognize them.")
NiceKnowledge.create(acronym: "K0134", description: "Knowledge of deployable forensics.")
NiceKnowledge.create(acronym: "K0135", description: "Knowledge of web filtering technologies.")
NiceKnowledge.create(acronym: "K0136", description: "Knowledge of the capabilities of different electronic communication systems and methods (e.g., e-mail, VOIP, IM, web forums, Direct Video Broadcasts).")
NiceKnowledge.create(acronym: "K0137", description: "Knowledge of the range of existing networks (e.g., PBX, LANs, WANs, WIFI, SCADA).")
NiceKnowledge.create(acronym: "K0138", description: "Knowledge of Wi-Fi.")
NiceKnowledge.create(acronym: "K0139", description: "Knowledge of interpreted and compiled computer languages.")
NiceKnowledge.create(acronym: "K0140", description: "Knowledge of secure coding techniques.")
NiceKnowledge.create(acronym: "K0141", description: "WITHDRAWN: Integrated into K0420")
NiceKnowledge.create(acronym: "K0142", description: "Knowledge of collection management processes, capabilities, and limitations.")
NiceKnowledge.create(acronym: "K0143", description: "Knowledge of front-end collection systems, including traffic collection, filtering, and selection.")
NiceKnowledge.create(acronym: "K0144", description: "Knowledge of social dynamics of computer attackers in a global context.")
NiceKnowledge.create(acronym: "K0145", description: "Knowledge of security event correlation tools.")
NiceKnowledge.create(acronym: "K0146", description: "Knowledge of the organization's core business/mission processes.")
NiceKnowledge.create(acronym: "K0147", description: "Knowledge of emerging security issues, risks, and vulnerabilities.")
NiceKnowledge.create(acronym: "K0148", description: "Knowledge of import/export control regulations and responsible agencies for the purposes of reducing supply chain risk.")
NiceKnowledge.create(acronym: "K0149", description: "Knowledge of organization's risk tolerance and/or risk management approach.")
NiceKnowledge.create(acronym: "K0150", description: "Knowledge of enterprise incident response program, roles, and responsibilities.")
NiceKnowledge.create(acronym: "K0151", description: "Knowledge of current and emerging threats/threat vectors.")
NiceKnowledge.create(acronym: "K0152", description: "Knowledge of software related information technology (IT) security principles and methods (e.g., modularization, layering, abstraction, data hiding, simplicity/minimization).")
NiceKnowledge.create(acronym: "K0153", description: "Knowledge of software quality assurance process.")
NiceKnowledge.create(acronym: "K0154", description: "Knowledge of supply chain risk management standards, processes, and practices.")
NiceKnowledge.create(acronym: "K0155", description: "Knowledge of electronic evidence law.")
NiceKnowledge.create(acronym: "K0156", description: "Knowledge of legal rules of evidence and court procedure.")
NiceKnowledge.create(acronym: "K0157", description: "Knowledge of cyber defense and information security policies, procedures, and regulations.")
NiceKnowledge.create(acronym: "K0158", description: "Knowledge of organizational information technology (IT) user security policies (e.g., account creation, password rules, access control).")
NiceKnowledge.create(acronym: "K0159", description: "Knowledge of Voice over IP (VoIP).")
NiceKnowledge.create(acronym: "K0160", description: "Knowledge of the common attack vectors on the network layer.")
NiceKnowledge.create(acronym: "K0161", description: "Knowledge of different classes of attacks (e.g., passive, active, insider, close-in, distribution attacks).")
NiceKnowledge.create(acronym: "K0162", description: "Knowledge of cyber attackers (e.g., script kiddies, insider threat, non-nation state sponsored, and nation sponsored).")
NiceKnowledge.create(acronym: "K0163", description: "Knowledge of critical information technology (IT) procurement requirements.")
NiceKnowledge.create(acronym: "K0164", description: "Knowledge of functionality, quality, and security requirements and how these will apply to specific items of supply (i.e., elements and processes).")
NiceKnowledge.create(acronym: "K0165", description: "Knowledge of risk/threat assessment.")
NiceKnowledge.create(acronym: "K0166", description: "WITHDRAWN: Knowledge of the nature and function of the relevant information structure. (See K0127)")
NiceKnowledge.create(acronym: "K0167", description: "Knowledge of system administration, network, and operating system hardening techniques.")
NiceKnowledge.create(acronym: "K0168", description: "Knowledge of applicable laws, statutes (e.g., in Titles 10, 18, 32, 50 in U.S. Code), Presidential Directives, executive branch guidelines, and/or administrative/criminal legal guidelines and procedures.")
NiceKnowledge.create(acronym: "K0169", description: "Knowledge of information technology (IT) supply chain security and supply chain risk management policies, requirements, and procedures.")
NiceKnowledge.create(acronym: "K0170", description: "Knowledge of critical infrastructure systems with information communication technology that were designed without system security considerations.")
NiceKnowledge.create(acronym: "K0171", description: "Knowledge of hardware reverse engineering techniques.")
NiceKnowledge.create(acronym: "K0172", description: "Knowledge of middleware (e.g., enterprise service bus and message queuing).")
NiceKnowledge.create(acronym: "K0173", description: "WITHDRAWN: Integrated into K0499 (prior to draft SP 800-181)")
NiceKnowledge.create(acronym: "K0174", description: "Knowledge of networking protocols.")
NiceKnowledge.create(acronym: "K0175", description: "Knowledge of software reverse engineering techniques.")
NiceKnowledge.create(acronym: "K0176", description: "Knowledge of Extensible Markup Language (XML) schemas.")
NiceKnowledge.create(acronym: "K0177", description: "Knowledge of cyber attack stages (e.g., reconnaissance, scanning, enumeration, gaining access, escalation of privileges, maintaining access, network exploitation, covering tracks).")
NiceKnowledge.create(acronym: "K0178", description: "Knowledge of secure software deployment methodologies, tools, and practices.")
NiceKnowledge.create(acronym: "K0179", description: "Knowledge of network security architecture concepts including topology, protocols, components, and principles (e.g., application of defense-in-depth).")
NiceKnowledge.create(acronym: "K0180", description: "Knowledge of network systems management principles, models, methods (e.g., end-to-end systems performance monitoring), and tools.")
NiceKnowledge.create(acronym: "K0181", description: "WITHDRAWN: Knowledge of transmission records (e.g., Bluetooth, Radio Frequency Identification [RFID], Infrared Networking [IR], Wireless Fidelity [Wi-Fi]. paging, cellular, satellite dishes), and jamming techniques that enable transmission of undesirable information, or prevent installed systems from operating correctly. (See K0274)")
NiceKnowledge.create(acronym: "K0182", description: "Knowledge of data carving tools and techniques (e.g., Foremost).")
NiceKnowledge.create(acronym: "K0183", description: "Knowledge of reverse engineering concepts.")
NiceKnowledge.create(acronym: "K0184", description: "Knowledge of anti-forensics tactics, techniques, and procedures.")
NiceKnowledge.create(acronym: "K0185", description: "Knowledge of forensics lab design configuration and support applications (e.g., VMWare, Wireshark).")
NiceKnowledge.create(acronym: "K0186", description: "Knowledge of debugging procedures and tools.")
NiceKnowledge.create(acronym: "K0187", description: "Knowledge of file type abuse by adversaries for anomalous behavior.")
NiceKnowledge.create(acronym: "K0188", description: "Knowledge of malware analysis tools (e.g., Oily Debug, Ida Pro).")
NiceKnowledge.create(acronym: "K0189", description: "Knowledge of malware with virtual machine detection (e.g. virtual aware malware, debugger aware malware, and unpacked malware that looks for VM-related strings in your computer’s display device).")
NiceKnowledge.create(acronym: "K0190", description: "Knowledge of encryption methodologies.")
NiceKnowledge.create(acronym: "K0191", description: "Knowledge of signature implementation impact for viruses, malware, and attacks.")
NiceKnowledge.create(acronym: "K0192", description: "Knowledge of Windows/Unix ports and services.")
NiceKnowledge.create(acronym: "K0193", description: "Knowledge of advanced data remediation security features in databases.")
NiceKnowledge.create(acronym: "K0194", description: "Knowledge of Cloud-based knowledge management technologies and concepts related to security, governance, procurement, and administration.")
NiceKnowledge.create(acronym: "K0195", description: "Knowledge of data classification standards and methodologies based on sensitivity and other risk factors.")
NiceKnowledge.create(acronym: "K0196", description: "Knowledge of Import/Export Regulations related to cryptography and other security technologies.")
NiceKnowledge.create(acronym: "K0197", description: "Knowledge of database access application programming interfaces (e.g., Java Database Connectivity [JDBC]).")
NiceKnowledge.create(acronym: "K0198", description: "Knowledge of organizational process improvement concepts and process maturity models (e.g., Capability Maturity Model Integration (CMMI) for Development, CMMI for Services, and CMMI for Acquisitions).")
NiceKnowledge.create(acronym: "K0199", description: "Knowledge of security architecture concepts and enterprise architecture reference models (e.g., Zachman, Federal Enterprise Architecture [FEA]).")
NiceKnowledge.create(acronym: "K0200", description: "Knowledge of service management concepts for networks and related standards (e.g., Information Technology Infrastructure Library, current version [ITIL]).")
NiceKnowledge.create(acronym: "K0201", description: "Knowledge of symmetric key rotation techniques and concepts.")
NiceKnowledge.create(acronym: "K0202", description: "Knowledge of the application firewall concepts and functions (e.g., Single point of authentication/audit/policy enforcement, message scanning for malicious content, data anonymization for PCI and PII compliance, data loss protection scanning, accelerated cryptographic operations, SSL security, REST/JSON processing).")
NiceKnowledge.create(acronym: "K0203", description: "Knowledge of security models (e.g., Bell-LaPadula model, Biba integrity model, Clark-Wilson integrity model).")
NiceKnowledge.create(acronym: "K0204", description: "Knowledge of learning assessment techniques (rubrics, evaluation plans, tests, quizzes).")
NiceKnowledge.create(acronym: "K0205", description: "Knowledge of basic system, network, and OS hardening techniques.")
NiceKnowledge.create(acronym: "K0206", description: "Knowledge of ethical hacking principles and techniques.")
NiceKnowledge.create(acronym: "K0207", description: "Knowledge of circuit analysis.")
NiceKnowledge.create(acronym: "K0208", description: "Knowledge of computer based training and e-learning services.")
NiceKnowledge.create(acronym: "K0209", description: "Knowledge of covert communication techniques.")
NiceKnowledge.create(acronym: "K0210", description: "Knowledge of data backup and restoration concepts.")
NiceKnowledge.create(acronym: "K0211", description: "Knowledge of confidentiality, integrity, and availability requirements.")
NiceKnowledge.create(acronym: "K0212", description: "Knowledge of cybersecurity-enabled software products.")
NiceKnowledge.create(acronym: "K0213", description: "Knowledge of instructional design and evaluation models (e.g., ADDIE, Smith/Ragan model, Gagne’s Events of Instruction, Kirkpatrick’s model of evaluation).")
NiceKnowledge.create(acronym: "K0214", description: "Knowledge of the Risk Management Framework Assessment Methodology.")
NiceKnowledge.create(acronym: "K0215", description: "Knowledge of organizational training policies.")
NiceKnowledge.create(acronym: "K0216", description: "Knowledge of learning levels (i.e., Bloom’s Taxonomy of learning).")
NiceKnowledge.create(acronym: "K0217", description: "Knowledge of Learning Management Systems and their use in managing learning.")
NiceKnowledge.create(acronym: "K0218", description: "Knowledge of learning styles (e.g., assimilator, auditory, kinesthetic).")
NiceKnowledge.create(acronym: "K0219", description: "WITHDRAWN: Knowledge of local area network (LAN) and wide area network (WAN) principles. (See K0050)")
NiceKnowledge.create(acronym: "K0220", description: "Knowledge of modes of learning (e.g., rote learning, observation).")
NiceKnowledge.create(acronym: "K0221", description: "Knowledge of OSI model and underlying network protocols (e.g., TCP/IP).")
NiceKnowledge.create(acronym: "K0222", description: "Knowledge of relevant laws, legal authorities, restrictions, and regulations pertaining to cyber defense activities.")
NiceKnowledge.create(acronym: "K0223", description: "WITHDRAWN: Integrated into K0073")
NiceKnowledge.create(acronym: "K0224", description: "Knowledge of system administration concepts for operating systems such as but not limited to Unix/Linux, IOS, Android, and Windows operating systems.")
NiceKnowledge.create(acronym: "K0225", description: "WITHDRAWN: Knowledge of the common networking protocol and services deployed at CC/S/A. (See K0565)")
NiceKnowledge.create(acronym: "K0226", description: "Knowledge of organizational training systems.")
NiceKnowledge.create(acronym: "K0227", description: "Knowledge of various types of computer architectures.")
NiceKnowledge.create(acronym: "K0228", description: "Knowledge of taxonomy and semantic ontology theory.")
NiceKnowledge.create(acronym: "K0229", description: "Knowledge of applications that can log errors, exceptions, and application faults and logging.")
NiceKnowledge.create(acronym: "K0230", description: "Knowledge of cloud service models and how those models can limit incident response.")
NiceKnowledge.create(acronym: "K0231", description: "Knowledge of crisis management protocols, processes, and techniques.")
NiceKnowledge.create(acronym: "K0232", description: "WITHDRAWN: Knowledge of critical protocols (e.g., IPSEC, AES, GRE, IKE).")
NiceKnowledge.create(acronym: "K0233", description: "Knowledge of the National Cybersecurity Workforce Framework, work roles, and associated tasks, knowledge, skills, and abilities.")
NiceKnowledge.create(acronym: "K0234", description: "Knowledge of full spectrum cyber capabilities (e.g., defense, attack, exploitation).")
NiceKnowledge.create(acronym: "K0235", description: "Knowledge of how to leverage research and development centers, think tanks, academic research, and industry systems.")
NiceKnowledge.create(acronym: "K0236", description: "Knowledge of how to utilize Hadoop, Java, Python, SQL, Hive, and Pig to explore data.")
NiceKnowledge.create(acronym: "K0237", description: "Knowledge of industry best practices for service desk.")
NiceKnowledge.create(acronym: "K0238", description: "Knowledge of machine learning theory and principles.")
NiceKnowledge.create(acronym: "K0239", description: "Knowledge of media production, communication, and dissemination techniques and methods, including alternative ways to inform via written, oral, and visual media.")
NiceKnowledge.create(acronym: "K0240", description: "Knowledge of multi-level security systems and cross domain solutions.")
NiceKnowledge.create(acronym: "K0241", description: "Knowledge of organizational human resource policies, processes, and procedures.")
NiceKnowledge.create(acronym: "K0242", description: "Knowledge of organizational security policies.")
NiceKnowledge.create(acronym: "K0243", description: "Knowledge of organizational training and education policies, processes, and procedures.")
NiceKnowledge.create(acronym: "K0244", description: "Knowledge of physical and physiological behaviors that may indicate suspicious or abnormal activity.")
NiceKnowledge.create(acronym: "K0245", description: "Knowledge of principles and processes for conducting training and education needs assessment.")
NiceKnowledge.create(acronym: "K0246", description: "Knowledge of relevant concepts, procedures, software, equipment, and technology applications.")
NiceKnowledge.create(acronym: "K0247", description: "Knowledge of remote access processes, tools, and capabilities related to customer support.")
NiceKnowledge.create(acronym: "K0248", description: "Knowledge of strategic theory and practice.")
NiceKnowledge.create(acronym: "K0249", description: "Knowledge of sustainment technologies, processes and strategies.")
NiceKnowledge.create(acronym: "K0250", description: "Knowledge of Test & Evaluation processes for learners.")
NiceKnowledge.create(acronym: "K0251", description: "Knowledge of the judicial process, including the presentation of facts and evidence.")
NiceKnowledge.create(acronym: "K0252", description: "Knowledge of training and education principles and methods for curriculum design, teaching and instruction for individuals and groups, and the measurement of training and education effects.")
NiceKnowledge.create(acronym: "K0253", description: "WITHDRAWN: Integrated into K0227")
NiceKnowledge.create(acronym: "K0254", description: "Knowledge of binary analysis.")
NiceKnowledge.create(acronym: "K0255", description: "Knowledge of network architecture concepts including topology, protocols, and components.")
NiceKnowledge.create(acronym: "K0256", description: "WITHDRAWN: Integrated into K0224")
NiceKnowledge.create(acronym: "K0257", description: "Knowledge of information technology (IT) acquisition/procurement requirements.")
NiceKnowledge.create(acronym: "K0258", description: "Knowledge of test procedures, principles, and methodologies (e.g., Capabilities and Maturity Model Integration (CMMI)).")
NiceKnowledge.create(acronym: "K0259", description: "Knowledge of malware analysis concepts and methodologies.")
NiceKnowledge.create(acronym: "K0260", description: "Knowledge of Personally Identifiable Information (PII) data security standards.")
NiceKnowledge.create(acronym: "K0261", description: "Knowledge of Payment Card Industry (PCI) data security standards.")
NiceKnowledge.create(acronym: "K0262", description: "Knowledge of Personal Health Information (PHI) data security standards.")
NiceKnowledge.create(acronym: "K0263", description: "Knowledge of information technology (IT) risk management policies, requirements, and procedures.")
NiceKnowledge.create(acronym: "K0264", description: "Knowledge of program protection planning (e.g. information technology (IT) supply chain security/risk management policies, anti-tampering techniques, and requirements).")
NiceKnowledge.create(acronym: "K0265", description: "Knowledge of infrastructure supporting information technology (IT) for safety, performance, and reliability.")
NiceKnowledge.create(acronym: "K0266", description: "Knowledge of how to evaluate the trustworthiness of the supplier and/or product.")
NiceKnowledge.create(acronym: "K0267", description: "Knowledge of laws, policies, procedures, or governance relevant to cybersecurity for critical infrastructures.")
NiceKnowledge.create(acronym: "K0268", description: "Knowledge of forensic footprint identification.")
NiceKnowledge.create(acronym: "K0269", description: "Knowledge of mobile communications architecture.")
NiceKnowledge.create(acronym: "K0270", description: "Knowledge of the acquisition/procurement life cycle process.")
NiceKnowledge.create(acronym: "K0271", description: "Knowledge of operating system structures and internals (e.g., process management, directory structure, installed applications).")
NiceKnowledge.create(acronym: "K0272", description: "Knowledge of network analysis tools used to identify software communications vulnerabilities.")
NiceKnowledge.create(acronym: "K0273", description: "WITHDRAWN: Knowledge of general kill chain (e.g., footprinting and scanning, enumeration, gaining access, escalation of privileges, maintaining access, network exploitation, covering tracks).")
NiceKnowledge.create(acronym: "K0274", description: "Knowledge of transmission records (e.g., Bluetooth, Radio Frequency Identification (RFID), Infrared Networking (IR), Wireless Fidelity (Wi-Fi). paging, cellular, satellite dishes, Voice over Internet Protocol (VoIP)), and jamming techniques that enable transmission of undesirable information, or prevent installed systems from operating correctly.")
NiceKnowledge.create(acronym: "K0275", description: "Knowledge of configuration management techniques.")
NiceKnowledge.create(acronym: "K0276", description: "Knowledge of security management.")
NiceKnowledge.create(acronym: "K0277", description: "Knowledge of current and emerging data encryption (e.g., Column and Tablespace Encryption, file and disk encryption) security features in databases (e.g. built-in cryptographic key management features).")
NiceKnowledge.create(acronym: "K0278", description: "Knowledge of current and emerging data remediation security features in databases.")
NiceKnowledge.create(acronym: "K0279", description: "WITHDRAWN: Knowledge of database access application programming interfaces (APIs) (e.g., Java Database Connectivity [JDBC]).")
NiceKnowledge.create(acronym: "K0280", description: "Knowledge of systems engineering theories, concepts, and methods.")
NiceKnowledge.create(acronym: "K0281", description: "Knowledge of information technology (IT) service catalogues.")
NiceKnowledge.create(acronym: "K0282", description: "WITHDRAWN: Integrated into K0200")
NiceKnowledge.create(acronym: "K0283", description: "Knowledge of use cases related to collaboration and content synchronization across platforms (e.g., Mobile, PC, Cloud).")
NiceKnowledge.create(acronym: "K0284", description: "Knowledge of developing and applying user credential management system.")
NiceKnowledge.create(acronym: "K0285", description: "Knowledge of implementing enterprise key escrow systems to support data-at-rest encryption.")
NiceKnowledge.create(acronym: "K0286", description: "Knowledge of N-tiered typologies (e.g. including server and client operating systems).")
NiceKnowledge.create(acronym: "K0287", description: "Knowledge of an organization's information classification program and procedures for information compromise.")
NiceKnowledge.create(acronym: "K0288", description: "Knowledge of industry standard security models.")
NiceKnowledge.create(acronym: "K0289", description: "Knowledge of system/server diagnostic tools and fault identification techniques.")
NiceKnowledge.create(acronym: "K0290", description: "Knowledge of systems security testing and evaluation methods.")
NiceKnowledge.create(acronym: "K0291", description: "Knowledge of the enterprise information technology (IT) architectural concepts and patterns (e.g., baseline, validated design, and target architectures.)")
NiceKnowledge.create(acronym: "K0292", description: "Knowledge of the operations and processes for incident, problem, and event management.")
NiceKnowledge.create(acronym: "K0293", description: "Knowledge of integrating the organization’s goals and objectives into the architecture.")
NiceKnowledge.create(acronym: "K0294", description: "Knowledge of IT system operation, maintenance, and security needed to keep equipment functioning properly.")
NiceKnowledge.create(acronym: "K0295", description: "Knowledge of confidentiality, integrity, and availability principles.")
NiceKnowledge.create(acronym: "K0296", description: "Knowledge of capabilities, applications, and potential vulnerabilities of network equipment including hubs, routers, switches, bridges, servers, transmission media, and related hardware.")
NiceKnowledge.create(acronym: "K0297", description: "Knowledge of countermeasure design for identified security risks.")
NiceKnowledge.create(acronym: "K0298", description: "Knowledge of countermeasures for identified security risks.")
NiceKnowledge.create(acronym: "K0299", description: "Knowledge in determining how a security system should work (including its resilience and dependability capabilities) and how changes in conditions, operations, or the environment will affect these outcomes.")
NiceKnowledge.create(acronym: "K0300", description: "Knowledge of network mapping and recreating network topologies.")
NiceKnowledge.create(acronym: "K0301", description: "Knowledge of packet-level analysis using appropriate tools (e.g., Wireshark, tcpdump).")
NiceKnowledge.create(acronym: "K0302", description: "Knowledge of the basic operation of computers.")
NiceKnowledge.create(acronym: "K0303", description: "Knowledge of the use of sub-netting tools.")
NiceKnowledge.create(acronym: "K0304", description: "Knowledge of concepts and practices of processing digital forensic data.")
NiceKnowledge.create(acronym: "K0305", description: "Knowledge of data concealment (e.g. encryption algorithms and steganography).")
NiceKnowledge.create(acronym: "K0306", description: "WITHDRAWN: Knowledge of basic physical computer components and architectures")
NiceKnowledge.create(acronym: "K0307", description: "WITHDRAWN: Knowledge of common network tools (e.g., ping, traceroute, nslookup). (See K0111)")
NiceKnowledge.create(acronym: "K0308", description: "Knowledge of cryptology.")
NiceKnowledge.create(acronym: "K0309", description: "Knowledge of emerging technologies that have potential for exploitation.")
NiceKnowledge.create(acronym: "K0310", description: "Knowledge of hacking methodologies.")
NiceKnowledge.create(acronym: "K0311", description: "Knowledge of industry indicators useful for identifying technology trends.")
NiceKnowledge.create(acronym: "K0312", description: "Knowledge of intelligence gathering principles, policies, and procedures including legal authorities and restrictions.")
NiceKnowledge.create(acronym: "K0313", description: "Knowledge of external organizations and academic institutions with cyber focus (e.g., cyber curriculum/training and Research & Development).")
NiceKnowledge.create(acronym: "K0314", description: "Knowledge of industry technologies’ potential cybersecurity vulnerabilities.")
NiceKnowledge.create(acronym: "K0315", description: "Knowledge of the principal methods, procedures, and techniques of gathering information and producing, reporting, and sharing information.")
NiceKnowledge.create(acronym: "K0316", description: "Knowledge of business or military operation plans, concept operation plans, orders, policies, and standing rules of engagement.")
NiceKnowledge.create(acronym: "K0317", description: "Knowledge of procedures used for documenting and querying reported incidents, problems, and events.")
NiceKnowledge.create(acronym: "K0318", description: "Knowledge of operating system command-line tools.")
NiceKnowledge.create(acronym: "K0319", description: "Knowledge of technical delivery capabilities and their limitations.")
NiceKnowledge.create(acronym: "K0320", description: "Knowledge of organization's evaluation and validation criteria.")
NiceKnowledge.create(acronym: "K0321", description: "Knowledge of engineering concepts as applied to computer architecture and associated computer hardware/software.")
NiceKnowledge.create(acronym: "K0322", description: "Knowledge of embedded systems.")
NiceKnowledge.create(acronym: "K0323", description: "Knowledge of system fault tolerance methodologies.")
NiceKnowledge.create(acronym: "K0324", description: "Knowledge of Intrusion Detection System (IDS)/Intrusion Prevention System (IPS) tools and applications.")
NiceKnowledge.create(acronym: "K0325", description: "Knowledge of Information Theory (e.g., source coding, channel coding, algorithm complexity theory, and data compression).")
NiceKnowledge.create(acronym: "K0326", description: "Knowledge of demilitarized zones.")
NiceKnowledge.create(acronym: "K0327", description: "WITHDRAWN: Knowledge of local area network (LAN), wide area network (WAN) and enterprise principles and concepts, including bandwidth management. (See K0050)")
NiceKnowledge.create(acronym: "K0328", description: "WITHDRAWN: Knowledge of mathematics, including logarithms, trigonometry, linear algebra, calculus, statistics, and operational analysis.")
NiceKnowledge.create(acronym: "K0329", description: "WITHDRAWN: Knowledge of statistics.")
NiceKnowledge.create(acronym: "K0330", description: "Knowledge of successful capabilities to identify the solutions to less common and more complex system problems.")
NiceKnowledge.create(acronym: "K0331", description: "WITHDRAWN: Knowledge of network protocols (e.g., Transmission Control Protocol (TCP), Internet Protocol (IP), Dynamic Host Configuration Protocol (DHCP)), and directory services (e.g., Domain Name System (DNS)). (See K0332)")
NiceKnowledge.create(acronym: "K0332", description: "Knowledge of network protocols such as TCP/IP, Dynamic Host Configuration, Domain Name System (DNS), and directory services.")
NiceKnowledge.create(acronym: "K0333", description: "Knowledge of network design processes, to include understanding of security objectives, operational objectives, and trade-offs.")
NiceKnowledge.create(acronym: "K0334", description: "Knowledge of network traffic analysis (tools, methodologies, processes).")
NiceKnowledge.create(acronym: "K0335", description: "Knowledge of current and emerging cyber technologies.")
NiceKnowledge.create(acronym: "K0336", description: "Knowledge of access authentication methods.")
NiceKnowledge.create(acronym: "K0337", description: "WITHDRAWN: Integrated into K0007")
NiceKnowledge.create(acronym: "K0338", description: "Knowledge of data mining techniques.")
NiceKnowledge.create(acronym: "K0339", description: "Knowledge of how to use network analysis tools to identify vulnerabilities.")
NiceKnowledge.create(acronym: "K0340", description: "WITHDRAWN: Knowledge of how traffic flows across the network (e.g., Transmission Control Protocol (TCP), Internet Protocol (IP), Open System Interconnection Model (OSI)).")
NiceKnowledge.create(acronym: "K0341", description: "Knowledge of foreign disclosure policies and import/export control regulations as related to cybersecurity.")
NiceKnowledge.create(acronym: "K0342", description: "Knowledge of penetration testing principles, tools, and techniques.")
NiceKnowledge.create(acronym: "K0343", description: "Knowledge of root cause analysis techniques.")
NiceKnowledge.create(acronym: "K0344", description: "Knowledge of an organization’s threat environment.")
NiceKnowledge.create(acronym: "K0345", description: "WITHDRAWN: Knowledge of cyber attackers (e.g., script kiddies, insider threat, non-nation state sponsored, and nation sponsored).")
NiceKnowledge.create(acronym: "K0346", description: "Knowledge of principles and methods for integrating system components.")
NiceKnowledge.create(acronym: "K0347", description: "Knowledge and understanding of operational design.")
NiceKnowledge.create(acronym: "K0348", description: "WITHDRAWN: Knowledge of a wide range of basic communications media concepts and terminology (e.g., computer and telephone networks, satellite, cable, wireless).")
NiceKnowledge.create(acronym: "K0349", description: "Knowledge of website types, administration, functions, and content management system (CMS).")
NiceKnowledge.create(acronym: "K0350", description: "Knowledge of accepted organization planning systems.")
NiceKnowledge.create(acronym: "K0351", description: "Knowledge of applicable statutes, laws, regulations and policies governing cyber targeting and exploitation.")
NiceKnowledge.create(acronym: "K0352", description: "Knowledge of forms of intelligence support needs, topics, and focus areas.")
NiceKnowledge.create(acronym: "K0353", description: "Knowledge of possible circumstances that would result in changing collection management authorities.")
NiceKnowledge.create(acronym: "K0354", description: "Knowledge of relevant reporting and dissemination procedures.")
NiceKnowledge.create(acronym: "K0355", description: "Knowledge of all-source reporting and dissemination procedures.")
NiceKnowledge.create(acronym: "K0356", description: "Knowledge of analytic tools and techniques for language, voice and/or graphic material.")
NiceKnowledge.create(acronym: "K0357", description: "WITHDRAWN: Knowledge of analytical constructs and their use in assessing the operational environment. (See K0224)")
NiceKnowledge.create(acronym: "K0358", description: "Knowledge of analytical standards and the purpose of intelligence confidence levels.")
NiceKnowledge.create(acronym: "K0359", description: "Knowledge of approved intelligence dissemination processes.")
NiceKnowledge.create(acronym: "K0360", description: "WITHDRAWN: Knowledge of assembly code.")
NiceKnowledge.create(acronym: "K0361", description: "Knowledge of asset availability, capabilities and limitations.")
NiceKnowledge.create(acronym: "K0362", description: "Knowledge of attack methods and techniques (DDoS, brute force, spoofing, etc.).")
NiceKnowledge.create(acronym: "K0363", description: "Knowledge of auditing and logging procedures (including server-based logging).")
NiceKnowledge.create(acronym: "K0364", description: "Knowledge of available databases and tools necessary to assess appropriate collection tasking.")
NiceKnowledge.create(acronym: "K0365", description: "WITHDRAWN: Knowledge of basic back-up and recovery procedures including different types of backups (e.g., full, incremental).")
NiceKnowledge.create(acronym: "K0366", description: "WITHDRAWN: Knowledge of basic computer components and architectures, including the functions of various peripherals.")
NiceKnowledge.create(acronym: "K0367", description: "Knowledge of penetration testing.")
NiceKnowledge.create(acronym: "K0368", description: "Knowledge of implants that enable cyber collection and/or preparation activities.")
NiceKnowledge.create(acronym: "K0369", description: "WITHDRAWN: Knowledge of basic malicious activity concepts (e.g., footprinting, scanning and enumeration).")
NiceKnowledge.create(acronym: "K0370", description: "WITHDRAWN: Knowledge of basic physical computer components and architecture, including the functions of various components and peripherals (e.g., CPUs, Network Interface Cards, data storage). (See K0109)")
NiceKnowledge.create(acronym: "K0371", description: "Knowledge of principles of the collection development processes (e.g., Dialed Number Recognition, Social Network Analysis).")
NiceKnowledge.create(acronym: "K0372", description: "Knowledge of programming concepts (e.g., levels, structures, compiled vs. interpreted languages).")
NiceKnowledge.create(acronym: "K0373", description: "Knowledge of basic software applications (e.g., data storage and backup, database applications) and the types of vulnerabilities that have been found in those applications.")
NiceKnowledge.create(acronym: "K0374", description: "WITHDRAWN: Knowledge of basic structure, architecture, and design of modern digital and telephony networks. (See K0599)")
NiceKnowledge.create(acronym: "K0375", description: "Knowledge of wireless applications vulnerabilities.")
NiceKnowledge.create(acronym: "K0376", description: "Knowledge of internal and external customers and partner organizations, including information needs, objectives, structure, capabilities, etc.")
NiceKnowledge.create(acronym: "K0377", description: "Knowledge of classification and control markings standards, policies and procedures.")
NiceKnowledge.create(acronym: "K0378", description: "WITHDRAWN: Knowledge of classification and control markings standards. (See K0377)")
NiceKnowledge.create(acronym: "K0379", description: "Knowledge of client organizations, including information needs, objectives, structure, capabilities, etc.")
NiceKnowledge.create(acronym: "K0380", description: "Knowledge of collaborative tools and environments.")
NiceKnowledge.create(acronym: "K0381", description: "Knowledge of collateral damage and estimating impact(s).")
NiceKnowledge.create(acronym: "K0382", description: "Knowledge of collection capabilities and limitations.")
NiceKnowledge.create(acronym: "K0383", description: "Knowledge of collection capabilities, accesses, performance specifications, and constraints utilized to satisfy collection plan.")
NiceKnowledge.create(acronym: "K0384", description: "Knowledge of collection management functionality (e.g., positions, functions, responsibilities, products, reporting requirements).")
NiceKnowledge.create(acronym: "K0385", description: "WITHDRAWN: Integrated into K0142")
NiceKnowledge.create(acronym: "K0386", description: "Knowledge of collection management tools.")
NiceKnowledge.create(acronym: "K0387", description: "Knowledge of collection planning process and collection plan.")
NiceKnowledge.create(acronym: "K0388", description: "Knowledge of collection searching/analyzing techniques and tools for chat/buddy list, emerging technologies, VOIP, Media Over IP, VPN, VSAT/wireless, web mail and cookies.")
NiceKnowledge.create(acronym: "K0389", description: "Knowledge of collection sources including conventional and non-conventional sources.")
NiceKnowledge.create(acronym: "K0390", description: "Knowledge of collection strategies.")
NiceKnowledge.create(acronym: "K0391", description: "Knowledge of collection systems, capabilities, and processes.")
NiceKnowledge.create(acronym: "K0392", description: "Knowledge of common computer/network infections (virus, Trojan, etc.) and methods of infection (ports, attachments, etc.).")
NiceKnowledge.create(acronym: "K0393", description: "Knowledge of common networking devices and their configurations.")
NiceKnowledge.create(acronym: "K0394", description: "Knowledge of common reporting databases and tools.")
NiceKnowledge.create(acronym: "K0395", description: "Knowledge of computer networking fundamentals (i.e., basic computer components of a network, types of networks, etc.).")
NiceKnowledge.create(acronym: "K0396", description: "Knowledge of computer programming concepts, including computer languages, programming, testing, debugging, and file types.")
NiceKnowledge.create(acronym: "K0397", description: "Knowledge of security concepts in operating systems (e.g., Linux, Unix.)")
NiceKnowledge.create(acronym: "K0398", description: "Knowledge of concepts related to websites (e.g., web servers/pages, hosting, DNS, registration, web languages such as HTML).")
NiceKnowledge.create(acronym: "K0399", description: "Knowledge of crisis action planning and time sensitive planning procedures.")
NiceKnowledge.create(acronym: "K0400", description: "Knowledge of crisis action planning for cyber operations.")
NiceKnowledge.create(acronym: "K0401", description: "Knowledge of criteria for evaluating collection products.")
NiceKnowledge.create(acronym: "K0402", description: "Knowledge of criticality and vulnerability factors (e.g., value, recuperation, cushion, countermeasures) for target selection and applicability to the cyber domain.")
NiceKnowledge.create(acronym: "K0403", description: "Knowledge of cryptologic capabilities, limitations, and contributions to cyber operations.")
NiceKnowledge.create(acronym: "K0404", description: "Knowledge of current collection requirements.")
NiceKnowledge.create(acronym: "K0405", description: "Knowledge of current computer-based intrusion sets.")
NiceKnowledge.create(acronym: "K0406", description: "Knowledge of current software and methodologies for active defense and system hardening.")
NiceKnowledge.create(acronym: "K0407", description: "Knowledge of customer information needs.")
NiceKnowledge.create(acronym: "K0408", description: "Knowledge of cyber actions (i.e. cyber defense, information gathering, environment preparation, cyber-attack) principles, capabilities, limitations, and effects.")
NiceKnowledge.create(acronym: "K0409", description: "Knowledge of cyber intelligence/information collection capabilities and repositories.")
NiceKnowledge.create(acronym: "K0410", description: "Knowledge of cyber laws and their effect on Cyber planning.")
NiceKnowledge.create(acronym: "K0411", description: "Knowledge of cyber laws and legal considerations and their effect on cyber planning.")
NiceKnowledge.create(acronym: "K0412", description: "Knowledge of cyber lexicon/terminology")
NiceKnowledge.create(acronym: "K0413", description: "Knowledge of cyber operation objectives, policies, and legalities.")
NiceKnowledge.create(acronym: "K0414", description: "Knowledge of cyber operations support or enabling processes.")
NiceKnowledge.create(acronym: "K0415", description: "Knowledge of cyber operations terminology/lexicon.")
NiceKnowledge.create(acronym: "K0416", description: "Knowledge of cyber operations.")
NiceKnowledge.create(acronym: "K0417", description: "Knowledge of data communications terminology (e.g., networking protocols, Ethernet, IP, encryption, optical devices, removable media).")
NiceKnowledge.create(acronym: "K0418", description: "Knowledge of data flow process for terminal or environment collection.")
NiceKnowledge.create(acronym: "K0419", description: "Knowledge of database administration and maintenance.")
NiceKnowledge.create(acronym: "K0420", description: "Knowledge of database theory.")
NiceKnowledge.create(acronym: "K0421", description: "Knowledge of databases, portals and associated dissemination vehicles.")
NiceKnowledge.create(acronym: "K0422", description: "Knowledge of deconfliction processes and procedures.")
NiceKnowledge.create(acronym: "K0423", description: "Knowledge of deconfliction reporting to include external organization interaction.")
NiceKnowledge.create(acronym: "K0424", description: "Knowledge of denial and deception techniques.")
NiceKnowledge.create(acronym: "K0425", description: "Knowledge of different organization objectives at all levels, including subordinate, lateral and higher.")
NiceKnowledge.create(acronym: "K0426", description: "Knowledge of dynamic and deliberate targeting.")
NiceKnowledge.create(acronym: "K0427", description: "Knowledge of encryption algorithms and cyber capabilities/tools (e.g., SSL, PGP).")
NiceKnowledge.create(acronym: "K0428", description: "Knowledge of encryption algorithms and tools for wireless local area networks (WLANs).")
NiceKnowledge.create(acronym: "K0429", description: "Knowledge of enterprise-wide information management.")
NiceKnowledge.create(acronym: "K0430", description: "Knowledge of evasion strategies and techniques.")
NiceKnowledge.create(acronym: "K0431", description: "Knowledge of evolving/emerging communications technologies.")
NiceKnowledge.create(acronym: "K0432", description: "Knowledge of existing, emerging, and long-range issues related to cyber operations strategy, policy, and organization.")
NiceKnowledge.create(acronym: "K0433", description: "Knowledge of forensic implications of operating system structure and operations.")
NiceKnowledge.create(acronym: "K0434", description: "WITHDRAWN: Knowledge of front-end collection systems, including traffic collection, filtering, and selection.")
NiceKnowledge.create(acronym: "K0435", description: "Knowledge of fundamental cyber concepts, principles, limitations, and effects.")
NiceKnowledge.create(acronym: "K0436", description: "Knowledge of fundamental cyber operations concepts, terminology/lexicon (i.e., environment preparation, cyber-attack, cyber defense), principles, capabilities, limitations, and effects.")
NiceKnowledge.create(acronym: "K0437", description: "Knowledge of general Supervisory control and data acquisition (SCADA) system components.")
NiceKnowledge.create(acronym: "K0438", description: "Knowledge of mobile cellular communications architecture (e.g., LTE, CDMA, GSM/EDGE and UMTS/HSPA).")
NiceKnowledge.create(acronym: "K0439", description: "Knowledge of governing authorities for targeting.")
NiceKnowledge.create(acronym: "K0440", description: "Knowledge of host-based security products and how those products affect exploitation and reduce vulnerability.")
NiceKnowledge.create(acronym: "K0441", description: "WITHDRAWN: Knowledge of how collection requirements and information needs are translated, tracked, and prioritized across the extended enterprise.")
NiceKnowledge.create(acronym: "K0442", description: "Knowledge of how converged technologies impact cyber operations (e.g., digital, telephony, wireless).")
NiceKnowledge.create(acronym: "K0443", description: "WITHDRAWN: Knowledge of how hubs, switches, routers work together in the design of a network. (See K0143)")
NiceKnowledge.create(acronym: "K0444", description: "Knowledge of how Internet applications work (SMTP email, web-based email, chat clients, VOIP).")
NiceKnowledge.create(acronym: "K0445", description: "Knowledge of how modern digital and telephony networks impact cyber operations.")
NiceKnowledge.create(acronym: "K0446", description: "Knowledge of how modern wireless communications systems impact cyber operations.")
NiceKnowledge.create(acronym: "K0447", description: "Knowledge of how to collect, view, and identify essential information on targets of interest from metadata (e.g., email, http).")
NiceKnowledge.create(acronym: "K0448", description: "Knowledge of how to establish priorities for resources.")
NiceKnowledge.create(acronym: "K0449", description: "Knowledge of how to extract, analyze, and use metadata.")
NiceKnowledge.create(acronym: "K0450", description: "WITHDRAWN: Integrated into K0036")
NiceKnowledge.create(acronym: "K0451", description: "Knowledge of identification and reporting processes.")
NiceKnowledge.create(acronym: "K0452", description: "Knowledge of implementing Unix and Windows systems that provide radius authentication and logging, DNS, mail, web service, FTP server, DHCP, firewall, and SNMP.")
NiceKnowledge.create(acronym: "K0453", description: "Knowledge of indications and warning.")
NiceKnowledge.create(acronym: "K0454", description: "Knowledge of information needs.")
NiceKnowledge.create(acronym: "K0455", description: "Knowledge of information security concepts, facilitating technologies and methods.")
NiceKnowledge.create(acronym: "K0456", description: "Knowledge of intelligence capabilities and limitations.")
NiceKnowledge.create(acronym: "K0457", description: "Knowledge of intelligence confidence levels.")
NiceKnowledge.create(acronym: "K0458", description: "Knowledge of intelligence disciplines.")
NiceKnowledge.create(acronym: "K0459", description: "Knowledge of intelligence employment requirements (i.e., logistical, communications support, maneuverability, legal restrictions, etc.).")
NiceKnowledge.create(acronym: "K0460", description: "Knowledge of intelligence preparation of the environment and similar processes.")
NiceKnowledge.create(acronym: "K0461", description: "Knowledge of intelligence production processes.")
NiceKnowledge.create(acronym: "K0462", description: "Knowledge of intelligence reporting principles, policies, procedures, and vehicles, including report formats, reportability criteria (requirements and priorities), dissemination practices, and legal authorities and restrictions.")
NiceKnowledge.create(acronym: "K0463", description: "Knowledge of intelligence requirements tasking systems.")
NiceKnowledge.create(acronym: "K0464", description: "Knowledge of intelligence support to planning, execution, and assessment.")
NiceKnowledge.create(acronym: "K0465", description: "Knowledge of internal and external partner cyber operations capabilities and tools.")
NiceKnowledge.create(acronym: "K0466", description: "Knowledge of internal and external partner intelligence processes and the development of information requirements and essential information.")
NiceKnowledge.create(acronym: "K0467", description: "Knowledge of internal and external partner organization capabilities and limitations (those with tasking, collection, processing, exploitation and dissemination responsibilities).")
NiceKnowledge.create(acronym: "K0468", description: "Knowledge of internal and external partner reporting.")
NiceKnowledge.create(acronym: "K0469", description: "Knowledge of internal tactics to anticipate and/or emulate threat capabilities and actions.")
NiceKnowledge.create(acronym: "K0470", description: "Knowledge of Internet and routing protocols.")
NiceKnowledge.create(acronym: "K0471", description: "Knowledge of Internet network addressing (IP addresses, classless inter-domain routing, TCP/UDP port numbering).")
NiceKnowledge.create(acronym: "K0472", description: "Knowledge of intrusion detection systems and signature development.")
NiceKnowledge.create(acronym: "K0473", description: "Knowledge of intrusion sets.")
NiceKnowledge.create(acronym: "K0474", description: "Knowledge of key cyber threat actors and their equities.")
NiceKnowledge.create(acronym: "K0475", description: "Knowledge of key factors of the operational environment and threat.")
NiceKnowledge.create(acronym: "K0476", description: "Knowledge of language processing tools and techniques.")
NiceKnowledge.create(acronym: "K0477", description: "Knowledge of leadership's Intent and objectives.")
NiceKnowledge.create(acronym: "K0478", description: "Knowledge of legal considerations in targeting.")
NiceKnowledge.create(acronym: "K0479", description: "Knowledge of malware analysis and characteristics.")
NiceKnowledge.create(acronym: "K0480", description: "Knowledge of malware.")
NiceKnowledge.create(acronym: "K0481", description: "Knowledge of methods and techniques used to detect various exploitation activities.")
NiceKnowledge.create(acronym: "K0482", description: "Knowledge of methods for ascertaining collection asset posture and availability.")
NiceKnowledge.create(acronym: "K0483", description: "Knowledge of methods to integrate and summarize information from any potential sources.")
NiceKnowledge.create(acronym: "K0484", description: "Knowledge of midpoint collection (process, objectives, organization, targets, etc.).")
NiceKnowledge.create(acronym: "K0485", description: "Knowledge of network administration.")
NiceKnowledge.create(acronym: "K0486", description: "Knowledge of network construction and topology.")
NiceKnowledge.create(acronym: "K0487", description: "Knowledge of network security (e.g., encryption, firewalls, authentication, honey pots, perimeter protection).")
NiceKnowledge.create(acronym: "K0488", description: "Knowledge of network security implementations (e.g., host-based IDS, IPS, access control lists), including their function and placement in a network.")
NiceKnowledge.create(acronym: "K0489", description: "Knowledge of network topology.")
NiceKnowledge.create(acronym: "K0490", description: "WITHDRAWN: Integrated into K0058")
NiceKnowledge.create(acronym: "K0491", description: "Knowledge of networking and Internet communications fundamentals (i.e. devices, device configuration, hardware, software, applications, ports/protocols, addressing, network architecture and infrastructure, routing, operating systems, etc.).")
NiceKnowledge.create(acronym: "K0492", description: "Knowledge of non-traditional collection methodologies.")
NiceKnowledge.create(acronym: "K0493", description: "Knowledge of obfuscation techniques (e.g., TOR/Onion/anonymizers, VPN/VPS, encryption).")
NiceKnowledge.create(acronym: "K0494", description: "Knowledge of objectives, situation, operational environment, and the status and disposition of internal and external partner collection capabilities available to support planning.")
NiceKnowledge.create(acronym: "K0495", description: "Knowledge of ongoing and future operations.")
NiceKnowledge.create(acronym: "K0496", description: "Knowledge of operational asset constraints.")
NiceKnowledge.create(acronym: "K0497", description: "Knowledge of operational effectiveness assessment.")
NiceKnowledge.create(acronym: "K0498", description: "Knowledge of operational planning processes.")
NiceKnowledge.create(acronym: "K0499", description: "Knowledge of operations security.")
NiceKnowledge.create(acronym: "K0500", description: "Knowledge of organization and/or partner collection systems, capabilities, and processes (e.g., collection and protocol processors).")
NiceKnowledge.create(acronym: "K0501", description: "Knowledge of organization cyber operations programs, strategies, and resources.")
NiceKnowledge.create(acronym: "K0502", description: "Knowledge of organization decision support tools and/or methods.")
NiceKnowledge.create(acronym: "K0503", description: "Knowledge of organization formats of resource and asset readiness reporting, its operational relevance and intelligence collection impact.")
NiceKnowledge.create(acronym: "K0504", description: "Knowledge of organization issues, objectives, and operations in cyber as well as regulations and policy directives governing cyber operations.")
NiceKnowledge.create(acronym: "K0505", description: "Knowledge of organization objectives and associated demand on collection management.")
NiceKnowledge.create(acronym: "K0506", description: "Knowledge of organization objectives, leadership priorities, and decision-making risks.")
NiceKnowledge.create(acronym: "K0507", description: "Knowledge of organization or partner exploitation of digital networks.")
NiceKnowledge.create(acronym: "K0508", description: "Knowledge of organization policies and planning concepts for partnering with internal and/or external organizations.")
NiceKnowledge.create(acronym: "K0509", description: "Knowledge of organizational and partner authorities, responsibilities, and contributions to achieving objectives.")
NiceKnowledge.create(acronym: "K0510", description: "Knowledge of organizational and partner policies, tools, capabilities, and procedures.")
NiceKnowledge.create(acronym: "K0511", description: "Knowledge of organizational hierarchy and cyber decision-making processes.")
NiceKnowledge.create(acronym: "K0512", description: "Knowledge of organizational planning concepts.")
NiceKnowledge.create(acronym: "K0513", description: "Knowledge of organizational priorities, legal authorities and requirements submission processes.")
NiceKnowledge.create(acronym: "K0514", description: "Knowledge of organizational structures and associated intelligence capabilities.")
NiceKnowledge.create(acronym: "K0515", description: "WITHDRAWN: Knowledge of OSI model and underlying networking protocols (e.g., TCP/IP).")
NiceKnowledge.create(acronym: "K0516", description: "Knowledge of physical and logical network devices and infrastructure to include hubs, switches, routers, firewalls, etc.")
NiceKnowledge.create(acronym: "K0517", description: "Knowledge of post implementation review (PIR) approval process.")
NiceKnowledge.create(acronym: "K0518", description: "Knowledge of planning activity initiation.")
NiceKnowledge.create(acronym: "K0519", description: "Knowledge of planning timelines adaptive, crisis action, and time-sensitive planning.")
NiceKnowledge.create(acronym: "K0520", description: "Knowledge of principles and practices related to target development such as target knowledge, associations, communication systems, and infrastructure.")
NiceKnowledge.create(acronym: "K0521", description: "Knowledge of priority information, how it is derived, where it is published, how to access, etc.")
NiceKnowledge.create(acronym: "K0522", description: "Knowledge of production exploitation and dissemination needs and architectures.")
NiceKnowledge.create(acronym: "K0523", description: "Knowledge of products and nomenclature of major vendors (e.g., security suites - Trend Micro, Symantec, McAfee, Outpost, and Panda) and how those products affect exploitation and reduce vulnerabilities.")
NiceKnowledge.create(acronym: "K0524", description: "Knowledge of relevant laws, regulations, and policies.")
NiceKnowledge.create(acronym: "K0525", description: "Knowledge of required intelligence planning products associated with cyber operational planning.")
NiceKnowledge.create(acronym: "K0526", description: "Knowledge of research strategies and knowledge management.")
NiceKnowledge.create(acronym: "K0527", description: "Knowledge of risk management and mitigation strategies.")
NiceKnowledge.create(acronym: "K0528", description: "Knowledge of satellite-based communication systems.")
NiceKnowledge.create(acronym: "K0529", description: "Knowledge of scripting")
NiceKnowledge.create(acronym: "K0530", description: "Knowledge of security hardware and software options, including the network artifacts they induce and their effects on exploitation.")
NiceKnowledge.create(acronym: "K0531", description: "Knowledge of security implications of software configurations.")
NiceKnowledge.create(acronym: "K0532", description: "Knowledge of specialized target language (e.g., acronyms, jargon, technical terminology, code words).")
NiceKnowledge.create(acronym: "K0533", description: "Knowledge of specific target identifiers, and their usage.")
NiceKnowledge.create(acronym: "K0534", description: "Knowledge of staff management, assignment, and allocation processes.")
NiceKnowledge.create(acronym: "K0535", description: "Knowledge of strategies and tools for target research.")
NiceKnowledge.create(acronym: "K0536", description: "Knowledge of structure, approach, and strategy of exploitation tools (e.g., sniffers, keyloggers) and techniques (e.g., gaining backdoor access, collecting/exfiltrating data, conducting vulnerability analysis of other systems in the network).")
NiceKnowledge.create(acronym: "K0537", description: "Knowledge of system administration concepts for the Unix/Linux and Windows operating systems (e.g., process management, directory structure, installed applications, Access Controls).")
NiceKnowledge.create(acronym: "K0538", description: "Knowledge of target and threat organization structures, critical capabilities, and critical vulnerabilities")
NiceKnowledge.create(acronym: "K0539", description: "Knowledge of target communication profiles and their key elements (e.g., target associations, activities, communication infrastructure).")
NiceKnowledge.create(acronym: "K0540", description: "Knowledge of target communication tools and techniques.")
NiceKnowledge.create(acronym: "K0541", description: "Knowledge of target cultural references, dialects, expressions, idioms, and abbreviations.")
NiceKnowledge.create(acronym: "K0542", description: "Knowledge of target development (i.e., concepts, roles, responsibilities, products, etc.).")
NiceKnowledge.create(acronym: "K0543", description: "Knowledge of target estimated repair and recuperation times.")
NiceKnowledge.create(acronym: "K0544", description: "Knowledge of target intelligence gathering and operational preparation techniques and life cycles.")
NiceKnowledge.create(acronym: "K0545", description: "Knowledge of target language(s).")
NiceKnowledge.create(acronym: "K0546", description: "Knowledge of target list development (i.e. Restricted, Joint, Candidate, etc.).")
NiceKnowledge.create(acronym: "K0547", description: "Knowledge of target methods and procedures.")
NiceKnowledge.create(acronym: "K0548", description: "Knowledge of target or threat cyber actors and procedures.")
NiceKnowledge.create(acronym: "K0549", description: "Knowledge of target vetting and validation procedures.")
NiceKnowledge.create(acronym: "K0550", description: "Knowledge of target, including related current events, communication profile, actors, and history (language, culture) and/or frame of reference.")
NiceKnowledge.create(acronym: "K0551", description: "Knowledge of targeting cycles.")
NiceKnowledge.create(acronym: "K0552", description: "Knowledge of tasking mechanisms.")
NiceKnowledge.create(acronym: "K0553", description: "Knowledge of tasking processes for organic and subordinate collection assets.")
NiceKnowledge.create(acronym: "K0554", description: "Knowledge of tasking, collection, processing, exploitation and dissemination.")
NiceKnowledge.create(acronym: "K0555", description: "Knowledge of TCP/IP networking protocols.")
NiceKnowledge.create(acronym: "K0556", description: "Knowledge of telecommunications fundamentals.")
NiceKnowledge.create(acronym: "K0557", description: "Knowledge of terminal or environmental collection (process, objectives, organization, targets, etc.).")
NiceKnowledge.create(acronym: "K0558", description: "Knowledge of the available tools and applications associated with collection requirements and collection management.")
NiceKnowledge.create(acronym: "K0559", description: "Knowledge of the basic structure, architecture, and design of converged applications.")
NiceKnowledge.create(acronym: "K0560", description: "Knowledge of the basic structure, architecture, and design of modern communication networks.")
NiceKnowledge.create(acronym: "K0561", description: "Knowledge of the basics of network security (e.g., encryption, firewalls, authentication, honey pots, perimeter protection).")
NiceKnowledge.create(acronym: "K0562", description: "Knowledge of the capabilities and limitations of new and emerging collection capabilities, accesses and/or processes.")
NiceKnowledge.create(acronym: "K0563", description: "Knowledge of the capabilities, limitations and tasking methodologies of internal and external collections as they apply to planned cyber activities.")
NiceKnowledge.create(acronym: "K0564", description: "Knowledge of the characteristics of targeted communication networks (e.g., capacity, functionality, paths, critical nodes).")
NiceKnowledge.create(acronym: "K0565", description: "Knowledge of the common networking and routing protocols (e.g. TCP/IP), services (e.g., web, mail, DNS), and how they interact to provide network communications.")
NiceKnowledge.create(acronym: "K0566", description: "Knowledge of the critical information requirements and how they're used in planning.")
NiceKnowledge.create(acronym: "K0567", description: "Knowledge of the data flow from collection origin to repositories and tools.")
NiceKnowledge.create(acronym: "K0568", description: "Knowledge of the definition of collection management and collection management authority.")
NiceKnowledge.create(acronym: "K0569", description: "Knowledge of the existent tasking, collection, processing, exploitation and dissemination architecture.")
NiceKnowledge.create(acronym: "K0570", description: "Knowledge of the factors of threat that could impact collection operations.")
NiceKnowledge.create(acronym: "K0571", description: "Knowledge of the feedback cycle in collection processes.")
NiceKnowledge.create(acronym: "K0572", description: "Knowledge of the functions and capabilities of internal teams that emulate threat activities to benefit the organization.")
NiceKnowledge.create(acronym: "K0573", description: "Knowledge of the fundamentals of digital forensics to extract actionable intelligence.")
NiceKnowledge.create(acronym: "K0574", description: "Knowledge of the impact of language analysis on on-net operator functions.")
NiceKnowledge.create(acronym: "K0575", description: "Knowledge of the impacts of internal and external partner staffing estimates.")
NiceKnowledge.create(acronym: "K0576", description: "Knowledge of the information environment.")
NiceKnowledge.create(acronym: "K0577", description: "Knowledge of the intelligence frameworks, processes, and related systems.")
NiceKnowledge.create(acronym: "K0578", description: "Knowledge of the intelligence requirements development and request for information processes.")
NiceKnowledge.create(acronym: "K0579", description: "Knowledge of the organization, roles and responsibilities of higher, lower and adjacent sub-elements.")
NiceKnowledge.create(acronym: "K0580", description: "Knowledge of the organization’s established format for collection plan.")
NiceKnowledge.create(acronym: "K0581", description: "Knowledge of the organization’s planning, operations and targeting cycles.")
NiceKnowledge.create(acronym: "K0582", description: "Knowledge of the organizational planning and staffing process.")
NiceKnowledge.create(acronym: "K0583", description: "Knowledge of the organizational plans/directives/guidance that describe objectives.")
NiceKnowledge.create(acronym: "K0584", description: "Knowledge of the organizational policies/procedures for temporary transfer of collection authority.")
NiceKnowledge.create(acronym: "K0585", description: "Knowledge of the organizational structure as it pertains to full spectrum cyber operations, including the functions, responsibilities, and interrelationships among distinct internal elements.")
NiceKnowledge.create(acronym: "K0586", description: "Knowledge of the outputs of course of action and exercise analysis.")
NiceKnowledge.create(acronym: "K0587", description: "Knowledge of the POC’s, databases, tools and applications necessary to establish environment preparation and surveillance products.")
NiceKnowledge.create(acronym: "K0588", description: "Knowledge of the priority information requirements from subordinate, lateral and higher levels of the organization.")
NiceKnowledge.create(acronym: "K0589", description: "Knowledge of the process used to assess the performance and impact of operations.")
NiceKnowledge.create(acronym: "K0590", description: "Knowledge of the processes to synchronize operational assessment procedures with the critical information requirement process.")
NiceKnowledge.create(acronym: "K0591", description: "Knowledge of the production responsibilities and organic analysis and production capabilities.")
NiceKnowledge.create(acronym: "K0592", description: "Knowledge of the purpose and contribution of target templates.")
NiceKnowledge.create(acronym: "K0593", description: "Knowledge of the range of cyber operations and their underlying intelligence support needs, topics, and focus areas.")
NiceKnowledge.create(acronym: "K0594", description: "Knowledge of the relationships between end states, objectives, effects, lines of operation, etc.")
NiceKnowledge.create(acronym: "K0595", description: "Knowledge of the relationships of operational objectives, intelligence requirements, and intelligence production tasks.")
NiceKnowledge.create(acronym: "K0596", description: "Knowledge of the request for information process.")
NiceKnowledge.create(acronym: "K0597", description: "Knowledge of the role of network operations in supporting and facilitating other organization operations.")
NiceKnowledge.create(acronym: "K0598", description: "Knowledge of the structure and intent of organization specific plans, guidance and authorizations.")
NiceKnowledge.create(acronym: "K0599", description: "Knowledge of the structure, architecture, and design of modern digital and telephony networks.")
NiceKnowledge.create(acronym: "K0600", description: "Knowledge of the structure, architecture, and design of modern wireless communications systems.")
NiceKnowledge.create(acronym: "K0601", description: "Knowledge of the systems/architecture/communications used for coordination.")
NiceKnowledge.create(acronym: "K0602", description: "Knowledge of collection disciplines and capabilities.")
NiceKnowledge.create(acronym: "K0603", description: "Knowledge of the ways in which targets or threats use the Internet.")
NiceKnowledge.create(acronym: "K0604", description: "Knowledge of threat and/or target systems.")
NiceKnowledge.create(acronym: "K0605", description: "Knowledge of tipping, cueing, mixing, and redundancy.")
NiceKnowledge.create(acronym: "K0606", description: "Knowledge of transcript development processes and techniques (e.g., verbatim, gist, summaries).")
NiceKnowledge.create(acronym: "K0607", description: "Knowledge of translation processes and techniques.")
NiceKnowledge.create(acronym: "K0608", description: "Knowledge of Unix/Linux and Windows operating systems structures and internals (e.g., process management, directory structure, installed applications).")
NiceKnowledge.create(acronym: "K0609", description: "Knowledge of virtual machine technologies.")
NiceKnowledge.create(acronym: "K0610", description: "Knowledge of virtualization products (VMware, Virtual PC).")
NiceKnowledge.create(acronym: "K0611", description: "WITHDRAWN: Integrated into K0131")
NiceKnowledge.create(acronym: "K0612", description: "Knowledge of what constitutes a “threat” to a network.")
NiceKnowledge.create(acronym: "K0613", description: "Knowledge of who the organization’s operational planners are, how and where they can be contacted, and what are their expectations.")
NiceKnowledge.create(acronym: "K0614", description: "Knowledge of wireless technologies (e.g., cellular, satellite, GSM) to include the basic structure, architecture, and design of modern wireless communications systems.")
NiceKnowledge.create(acronym: "K0615", description: "Knowledge of privacy disclosure statements based on current laws.")
NiceKnowledge.create(acronym: "K0616", description: "Knowledge of continuous monitoring, its processes, and Continuous Diagnostics and Mitigation (CDM) program activities.")
NiceKnowledge.create(acronym: "K0617", description: "Knowledge of Automated security control assessments")
NiceKnowledge.create(acronym: "K0618", description: "Knowledge of hardware asset management and the value of tracking the location and configuration of networked devices and software across departments, locations, facilities and, potentially, supporting business functions.")
NiceKnowledge.create(acronym: "K0619", description: "Knowledge of software asset management and the value of tracking the location and configuration of networked devices and software across departments, locations, facilities and, potentially, supporting business functions.")
NiceKnowledge.create(acronym: "K0620", description: "Knowledge of continuous monitoring technologies and tools.")
NiceKnowledge.create(acronym: "K0621", description: "Knowledge of risk scoring.")
NiceKnowledge.create(acronym: "K0622", description: "Knowledge of controls related to the use, processing, storage, and transmission of data.")
NiceKnowledge.create(acronym: "K0623", description: "Knowledge of risk assessment methodologies.")
NiceKnowledge.create(acronym: "K0624", description: "Knowledge of Application Security Risks (e.g. Open Web Application Security Project Top 10 list)")
NiceKnowledge.create(acronym: "K0625", description: "Knowledge that patching and software updates are impractical for some networked devices.")
NiceKnowledge.create(acronym: "K0626", description: "Knowledge of secure update mechanisms.")
NiceKnowledge.create(acronym: "K0627", description: "Knowledge of the importance of ingress filtering to protect against automated threats that rely on spoofed network addresses.")
NiceKnowledge.create(acronym: "K0628", description: "Knowledge of cyber competitions as a way of developing skills by providing hands-on experience in simulated, real-world situations.")
NiceKnowledge.create(acronym: "K0629", description: "Knowledge of white/black listing")
NiceKnowledge.create(acronym: "K0630", description:	"Knowledge of the latest intrusion techniques, methods and documented intrusions external to the organization.")

puts "Created #{NiceKnowledge.count} NICE knowledges."