NiceSkill.destroy_all

NiceSkill.create(acronym: "S0001", description: "Skill in conducting vulnerability scans and recognizing vulnerabilities in security systems.")
NiceSkill.create(acronym: "S0002", description: "Skill in allocating storage capacity in the design of data management systems.")
NiceSkill.create(acronym: "S0003", description: "Skill of identifying, capturing, containing, and reporting malware.")
NiceSkill.create(acronym: "S0004", description: "Skill in analyzing network traffic capacity and performance characteristics.")
NiceSkill.create(acronym: "S0005", description: "Skill in applying and incorporating information technologies into proposed solutions.")
NiceSkill.create(acronym: "S0006", description: "Skill in applying confidentiality, integrity, and availability principles.")
NiceSkill.create(acronym: "S0007", description: "Skill in applying host/network access controls (e.g., access control list).")
NiceSkill.create(acronym: "S0008", description: "Skill in applying organization-specific systems analysis principles and techniques.")
NiceSkill.create(acronym: "S0009", description: "WITHDRAWN: Skill in assessing the robustness of security systems and designs. (See S0027)")
NiceSkill.create(acronym: "S0010", description: "Skill in conducting capabilities and requirements analysis.")
NiceSkill.create(acronym: "S0011", description: "Skill in conducting information searches.")
NiceSkill.create(acronym: "S0012", description: "Skill in conducting knowledge mapping (e.g., map of knowledge repositories).")
NiceSkill.create(acronym: "S0013", description: "Skill in conducting queries and developing algorithms to analyze data structures.")
NiceSkill.create(acronym: "S0014", description: "Skill in conducting software debugging.")
NiceSkill.create(acronym: "S0015", description: "Skill in conducting test events.")
NiceSkill.create(acronym: "S0016", description: "Skill in configuring and optimizing software.")
NiceSkill.create(acronym: "S0017", description: "Skill in creating and utilizing mathematical or statistical models.")
NiceSkill.create(acronym: "S0018", description: "Skill in creating policies that reflect system security objectives.")
NiceSkill.create(acronym: "S0019", description: "Skill in creating programs that validate and process multiple inputs including command line arguments, environmental variables, and input streams.")
NiceSkill.create(acronym: "S0020", description: "Skill in developing and deploying signatures.")
NiceSkill.create(acronym: "S0021", description: "Skill in designing a data analysis structure (i.e., the types of data a test must generate and how to analyze that data).")
NiceSkill.create(acronym: "S0022", description: "Skill in designing countermeasures to identified security risks.")
NiceSkill.create(acronym: "S0023", description: "Skill in designing security controls based on cybersecurity principles and tenets.")
NiceSkill.create(acronym: "S0024", description: "Skill in designing the integration of hardware and software solutions.")
NiceSkill.create(acronym: "S0025", description: "Skill in detecting host and network based intrusions via intrusion detection technologies (e.g., Snort).")
NiceSkill.create(acronym: "S0026", description: "Skill in determining an appropriate level of test rigor for a given system.")
NiceSkill.create(acronym: "S0027", description: "Skill in determining how a security system should work (including its resilience and dependability capabilities) and how changes in conditions, operations, or the environment will affect these outcomes.")
NiceSkill.create(acronym: "S0028", description: "Skill in developing data dictionaries.")
NiceSkill.create(acronym: "S0029", description: "Skill in developing data models.")
NiceSkill.create(acronym: "S0030", description: "Skill in developing operations-based testing scenarios.")
NiceSkill.create(acronym: "S0031", description: "Skill in developing and applying security system access controls.")
NiceSkill.create(acronym: "S0032", description: "Skill in developing, testing, and implementing network infrastructure contingency and recovery plans.")
NiceSkill.create(acronym: "S0033", description: "Skill in diagnosing connectivity problems.")
NiceSkill.create(acronym: "S0034", description: "Skill in discerning the protection needs (i.e., security controls) of information systems and networks.")
NiceSkill.create(acronym: "S0035", description: "Skill in establishing a routing schema.")
NiceSkill.create(acronym: "S0036", description: "Skill in evaluating the adequacy of security designs.")
NiceSkill.create(acronym: "S0037", description: "Skill in generating queries and reports.")
NiceSkill.create(acronym: "S0038", description: "Skill in identifying measures or indicators of system performance and the actions needed to improve or correct performance, relative to the goals of the system.")
NiceSkill.create(acronym: "S0039", description: "Skill in identifying possible causes of degradation of system performance or availability and initiating actions needed to mitigate this degradation.")
NiceSkill.create(acronym: "S0040", description: "Skill in implementing, maintaining, and improving established network security practices.")
NiceSkill.create(acronym: "S0041", description: "Skill in installing, configuring, and troubleshooting LAN and WAN components such as routers, hubs, and switches.")
NiceSkill.create(acronym: "S0042", description: "Skill in maintaining databases. (i.e., backup, restore, delete data, transaction log files, etc.).")
NiceSkill.create(acronym: "S0043", description: "Skill in maintaining directory services. (e.g., Microsoft Active Directory, LDAP, etc.).")
NiceSkill.create(acronym: "S0044", description: "Skill in mimicking threat behaviors.")
NiceSkill.create(acronym: "S0045", description: "Skill in optimizing database performance.")
NiceSkill.create(acronym: "S0046", description: "Skill in performing packet-level analysis using appropriate tools (e.g., Wireshark, tcpdump).")
NiceSkill.create(acronym: "S0047", description: "Skill in preserving evidence integrity according to standard operating procedures or national standards.")
NiceSkill.create(acronym: "S0048", description: "Skill in systems integration testing.")
NiceSkill.create(acronym: "S0049", description: "Skill in the measuring and reporting of intellectual capital.")
NiceSkill.create(acronym: "S0050", description: "Skill in design modeling and building use cases (e.g., unified modeling language).")
NiceSkill.create(acronym: "S0051", description: "Skill in the use of penetration testing tools and techniques.")
NiceSkill.create(acronym: "S0052", description: "Skill in the use of social engineering techniques. (e.g., phishing, baiting, tailgating, etc.).")
NiceSkill.create(acronym: "S0053", description: "Skill in tuning sensors.")
NiceSkill.create(acronym: "S0054", description: "Skill in using incident handling methodologies.")
NiceSkill.create(acronym: "S0055", description: "Skill in using knowledge management technologies.")
NiceSkill.create(acronym: "S0056", description: "Skill in using network management tools to analyze network traffic patterns (e.g., simple network management protocol).")
NiceSkill.create(acronym: "S0057", description: "Skill in using protocol analyzers.")
NiceSkill.create(acronym: "S0058", description: "Skill in using the appropriate tools for repairing software, hardware, and peripheral equipment of a system.")
NiceSkill.create(acronym: "S0059", description: "Skill in using Virtual Private Network (VPN) devices and encryption.")
NiceSkill.create(acronym: "S0060", description: "Skill in writing code in a currently supported programming language (e.g., Java, C++).")
NiceSkill.create(acronym: "S0061", description: "Skill in writing test plans.")
NiceSkill.create(acronym: "S0062", description: "Skill in analyzing memory dumps to extract information.")
NiceSkill.create(acronym: "S0063", description: "Skill in collecting data from a variety of cyber defense resources.")
NiceSkill.create(acronym: "S0064", description: "Skill in developing and executing technical training programs and curricula.")
NiceSkill.create(acronym: "S0065", description: "Skill in identifying and extracting data of forensic interest in diverse media (i.e., media forensics).")
NiceSkill.create(acronym: "S0066", description: "Skill in identifying gaps in technical capabilities.")
NiceSkill.create(acronym: "S0067", description: "Skill in identifying, modifying, and manipulating applicable system components within Windows, Unix, or Linux (e.g., passwords, user accounts, files).")
NiceSkill.create(acronym: "S0068", description: "Skill in collecting, processing, packaging, transporting, and storing electronic evidence to avoid alteration, loss, physical damage, or destruction of data.")
NiceSkill.create(acronym: "S0069", description: "Skill in setting up a forensic workstation.")
NiceSkill.create(acronym: "S0070", description: "Skill in talking to others to convey information effectively.")
NiceSkill.create(acronym: "S0071", description: "Skill in using forensic tool suites (e.g., EnCase, Sleuthkit, FTK).")
NiceSkill.create(acronym: "S0072", description: "Skill in using scientific rules and methods to solve problems.")
NiceSkill.create(acronym: "S0073", description: "Skill in using virtual machines. (e.g., Microsoft Hyper-V, VMWare vSphere, Citrix XenDesktop/Server, Amazon Elastic Compute Cloud, etc.).")
NiceSkill.create(acronym: "S0074", description: "Skill in physically disassembling PCs.")
NiceSkill.create(acronym: "S0075", description: "Skill in conducting forensic analyses in multiple operating system environments (e.g., mobile device systems).")
NiceSkill.create(acronym: "S0076", description: "Skill in configuring and utilizing software-based computer protection tools (e.g., software firewalls, antivirus software, anti-spyware).")
NiceSkill.create(acronym: "S0077", description: "Skill in securing network communications.")
NiceSkill.create(acronym: "S0078", description: "Skill in recognizing and categorizing types of vulnerabilities and associated attacks.")
NiceSkill.create(acronym: "S0079", description: "Skill in protecting a network against malware. (e.g., NIPS, anti-malware, restrict/prevent external devices, spam filters).")
NiceSkill.create(acronym: "S0080", description: "Skill in performing damage assessments.")
NiceSkill.create(acronym: "S0081", description: "Skill in using network analysis tools to identify vulnerabilities. (e.g., fuzzing, nmap, etc.).")
NiceSkill.create(acronym: "S0082", description: "Skill in evaluating test plans for applicability and completeness.")
NiceSkill.create(acronym: "S0083", description: "Skill in integrating black box security testing tools into quality assurance process of software releases.")
NiceSkill.create(acronym: "S0084", description: "Skill in configuring and utilizing network protection components (e.g., Firewalls, VPNs, network intrusion detection systems).")
NiceSkill.create(acronym: "S0085", description: "Skill in conducting audits or reviews of technical systems.")
NiceSkill.create(acronym: "S0086", description: "Skill in evaluating the trustworthiness of the supplier and/or product.")
NiceSkill.create(acronym: "S0087", description: "Skill in deep analysis of captured malicious code (e.g., malware forensics).")
NiceSkill.create(acronym: "S0088", description: "Skill in using binary analysis tools (e.g., Hexedit, command code xxd, hexdump).")
NiceSkill.create(acronym: "S0089", description: "Skill in one-way hash functions (e.g., Secure Hash Algorithm [SHA], Message Digest Algorithm [MD5]).")
NiceSkill.create(acronym: "S0090", description: "Skill in analyzing anomalous code as malicious or benign.")
NiceSkill.create(acronym: "S0091", description: "Skill in analyzing volatile data.")
NiceSkill.create(acronym: "S0092", description: "Skill in identifying obfuscation techniques.")
NiceSkill.create(acronym: "S0093", description: "Skill in interpreting results of debugger to ascertain tactics, techniques, and procedures.")
NiceSkill.create(acronym: "S0094", description: "Skill in reading Hexadecimal data.")
NiceSkill.create(acronym: "S0095", description: "Skill in identifying common encoding techniques (e.g., Exclusive Disjunction [XOR], American Standard Code for Information Interchange [ASCII], Unicode, Base64, Uuencode, Uniform Resource Locator [URL] encode).")
NiceSkill.create(acronym: "S0096", description: "Skill in reading and interpreting signatures (e.g., snort).")
NiceSkill.create(acronym: "S0097", description: "Skill in applying security controls.")
NiceSkill.create(acronym: "S0098", description: "WITHDRAWN: Skill in detecting host and network based intrusions via intrusion detection technologies. (See S0025)")
NiceSkill.create(acronym: "S0099", description: "WITHDRAWN: Skill in determining how a security system should work and how changes in conditions, operations, or the environment will affect these outcomes. (See S0027)")
NiceSkill.create(acronym: "S0100", description: "Skill in utilizing or developing learning activities (e.g., scenarios, instructional games, interactive exercises). ")
NiceSkill.create(acronym: "S0101", description: "Skill in utilizing technologies (e.g., SmartBoards, websites, computers, projectors) for instructional purposes. ")
NiceSkill.create(acronym: "S0102", description: "Skill in applying technical delivery capabilities.")
NiceSkill.create(acronym: "S0103", description: "Skill in assessing the predictive power and subsequent generalizability of a model.")
NiceSkill.create(acronym: "S0104", description: "Skill in conducting Test Readiness Reviews.")
NiceSkill.create(acronym: "S0105", description: "WITHDRAWN: Skill in data mining techniques. (See S0202)")
NiceSkill.create(acronym: "S0106", description: "Skill in data pre-processing (e.g., imputation, dimensionality reduction, normalization, transformation, extraction, filtering, smoothing).")
NiceSkill.create(acronym: "S0107", description: "Skill in designing and documenting overall program Test & Evaluation strategies.")
NiceSkill.create(acronym: "S0108", description: "Skill in developing workforce and position qualification standards.")
NiceSkill.create(acronym: "S0109", description: "Skill in identifying hidden patterns or relationships.")
NiceSkill.create(acronym: "S0110", description: "Skill in identifying Test & Evaluation infrastructure (people, ranges, tools, instrumentation) requirements.")
NiceSkill.create(acronym: "S0111", description: "Skill in interfacing with customers.")
NiceSkill.create(acronym: "S0112", description: "Skill in managing test assets, test resources, and test personnel to ensure effective completion of test events.")
NiceSkill.create(acronym: "S0113", description: "Skill in performing format conversions to create a standard representation of the data.")
NiceSkill.create(acronym: "S0114", description: "Skill in performing sensitivity analysis.")
NiceSkill.create(acronym: "S0115", description: "Skill in preparing Test & Evaluation reports.")
NiceSkill.create(acronym: "S0116", description: "Skill in designing multi-level security/cross domain solutions.")
NiceSkill.create(acronym: "S0117", description: "Skill in providing Test & Evaluation resource estimate.")
NiceSkill.create(acronym: "S0118", description: "Skill in developing machine understandable semantic ontologies.")
NiceSkill.create(acronym: "S0119", description: "Skill in Regression Analysis (e.g., Hierarchical Stepwise, Generalized Linear Model, Ordinary Least Squares, Tree-Based Methods, Logistic).")
NiceSkill.create(acronym: "S0120", description: "Skill in reviewing logs to identify evidence of past intrusions.")
NiceSkill.create(acronym: "S0121", description: "Skill in system, network, and OS hardening techniques. (e.g., remove unnecessary services, password policies, network segmentation, enable logging, least privilege, etc.).")
NiceSkill.create(acronym: "S0122", description: "Skill in the use of design methods. ")
NiceSkill.create(acronym: "S0123", description: "Skill in transformation analytics (e.g., aggregation, enrichment, processing).")
NiceSkill.create(acronym: "S0124", description: "Skill in troubleshooting and diagnosing cyber defense infrastructure anomalies and work through resolution.")
NiceSkill.create(acronym: "S0125", description: "Skill in using basic descriptive statistics and techniques (e.g., normality, model distribution, scatter plots).")
NiceSkill.create(acronym: "S0126", description: "Skill in using data analysis tools (e.g., Excel, STATA SAS, SPSS).")
NiceSkill.create(acronym: "S0127", description: "Skill in using data mapping tools.")
NiceSkill.create(acronym: "S0128", description: "Skill in using manpower and personnel IT systems.")
NiceSkill.create(acronym: "S0129", description: "Skill in using outlier identification and removal techniques.")
NiceSkill.create(acronym: "S0130", description: "Skill in writing scripts using R, Python, PIG, HIVE, SQL, etc.")
NiceSkill.create(acronym: "S0131", description: "Skill in analyzing malware.")
NiceSkill.create(acronym: "S0132", description: "Skill in conducting bit-level analysis.")
NiceSkill.create(acronym: "S0133", description: "Skill in processing digital evidence, to include protecting and making legally sound copies of evidence.")
NiceSkill.create(acronym: "S0134", description: "Skill in conducting reviews of systems.")
NiceSkill.create(acronym: "S0135", description: "Skill in secure test plan design (e. g. unit, integration, system, acceptance).")
NiceSkill.create(acronym: "S0136", description: "Skill in network systems management principles, models, methods (e.g., end-to-end systems performance monitoring), and tools.")
NiceSkill.create(acronym: "S0137", description: "Skill in conducting application vulnerability assessments.")
NiceSkill.create(acronym: "S0138", description: "Skill in using Public-Key Infrastructure (PKI) encryption and digital signature capabilities into applications (e.g., S/MIME email, SSL traffic).")
NiceSkill.create(acronym: "S0139", description: "Skill in applying security models (e.g., Bell-LaPadula model, Biba integrity model, Clark-Wilson integrity model).")
NiceSkill.create(acronym: "S0140", description: "Skill in applying the systems engineering process.")
NiceSkill.create(acronym: "S0141", description: "Skill in assessing security systems designs.")
NiceSkill.create(acronym: "S0142", description: "Skill in conducting research for troubleshooting novel client-level problems.")
NiceSkill.create(acronym: "S0143", description: "Skill in conducting system/server planning, management, and maintenance.")
NiceSkill.create(acronym: "S0144", description: "Skill in correcting physical and technical problems that impact system/server performance.")
NiceSkill.create(acronym: "S0145", description: "Skill in integrating and applying policies that meet system security objectives.")
NiceSkill.create(acronym: "S0146", description: "Skill in creating policies that enable systems to meet performance objectives (e.g. traffic routing, SLA's, CPU specifications).")
NiceSkill.create(acronym: "S0147", description: "Skill in assessing security controls based on cybersecurity principles and tenets. (e.g., CIS CSC, NIST SP 800-53, Cybersecurity Framework, etc.).")
NiceSkill.create(acronym: "S0148", description: "Skill in designing the integration of technology processes and solutions, including legacy systems and modern programming languages. ")
NiceSkill.create(acronym: "S0149", description: "Skill in developing applications that can log and handle errors, exceptions, and application faults and logging.")
NiceSkill.create(acronym: "S0150", description: "Skill in implementing and testing network infrastructure contingency and recovery plans.")
NiceSkill.create(acronym: "S0151", description: "Skill in troubleshooting failed system components (i.e., servers)")
NiceSkill.create(acronym: "S0152", description: "Skill in translating operational requirements into protection needs (i.e., security controls).")
NiceSkill.create(acronym: "S0153", description: "Skill in identifying and anticipating system/server performance, availability, capacity, or configuration problems.")
NiceSkill.create(acronym: "S0154", description: "Skill in installing system and component upgrades. (i.e., servers, appliances, network devices).")
NiceSkill.create(acronym: "S0155", description: "Skill in monitoring and optimizing system/server performance.")
NiceSkill.create(acronym: "S0156", description: "Skill in performing packet-level analysis.")
NiceSkill.create(acronym: "S0157", description: "Skill in recovering failed systems/servers. (e.g., recovery software, failover clusters, replication, etc.).")
NiceSkill.create(acronym: "S0158", description: "Skill in operating system administration. (e.g., account maintenance, data backups, maintain system performance, install and configure new hardware/software).")
NiceSkill.create(acronym: "S0159", description: "Skill in configuring and validating network workstations and peripherals in accordance with approved standards and/or specifications.")
NiceSkill.create(acronym: "S0160", description: "Skill in the use of design modeling (e.g., unified modeling language).")
NiceSkill.create(acronym: "S0161", description: "WITHDRAWN: Integrated into S0160")
NiceSkill.create(acronym: "S0162", description: "Skill in applying various subnet techniques (e.g., CIDR)")
NiceSkill.create(acronym: "S0163", description: "WITHDRAWN: Integrated into S0060")
NiceSkill.create(acronym: "S0164", description: "Skill in assessing the application of cryptographic standards.")
NiceSkill.create(acronym: "S0165", description: "WITHDRAWN: Skill in collecting, packaging, transporting, and storing electronic evidence to avoid alteration, loss, physical damage, or destruction of data. (See S0068)")
NiceSkill.create(acronym: "S0166", description: "Skill in identifying gaps in technical delivery capabilities.")
NiceSkill.create(acronym: "S0167", description: "Skill in recognizing vulnerabilities in security systems. (e.g., vulnerability and compliance scanning).")
NiceSkill.create(acronym: "S0168", description: "Skill in setting up physical or logical sub-networks that separate an internal local area network (LAN) from other untrusted networks.")
NiceSkill.create(acronym: "S0169", description: "Skill in conducting trend analysis.")
NiceSkill.create(acronym: "S0170", description: "Skill in configuring and utilizing computer protection components (e.g., hardware firewalls, servers, routers, as appropriate).")
NiceSkill.create(acronym: "S0171", description: "Skill in performing impact/risk assessments.")
NiceSkill.create(acronym: "S0172", description: "Skill in applying secure coding techniques. ")
NiceSkill.create(acronym: "S0173", description: "Skill in using security event correlation tools.")
NiceSkill.create(acronym: "S0174", description: "Skill in using code analysis tools.")
NiceSkill.create(acronym: "S0175", description: "Skill in performing root cause analysis.")
NiceSkill.create(acronym: "S0176", description: "Skill in administrative planning activities, to include preparation of functional and specific support plans, preparing and managing correspondence, and staffing procedures.")
NiceSkill.create(acronym: "S0177", description: "Skill in analyzing a target's communication networks.")
NiceSkill.create(acronym: "S0178", description: "Skill in analyzing essential network data (e.g., router configuration files, routing protocols).")
NiceSkill.create(acronym: "S0179", description: "Skill in analyzing language processing tools to provide feedback to enhance tool development.")
NiceSkill.create(acronym: "S0180", description: "WITHDRAWN: Integrated into S0062")
NiceSkill.create(acronym: "S0181", description: "Skill in analyzing midpoint collection data.")
NiceSkill.create(acronym: "S0182", description: "Skill in analyzing target communications internals and externals collected from wireless LANs.")
NiceSkill.create(acronym: "S0183", description: "Skill in analyzing terminal or environment collection data.")
NiceSkill.create(acronym: "S0184", description: "Skill in analyzing traffic to identify network devices.")
NiceSkill.create(acronym: "S0185", description: "Skill in applying analytical methods typically employed to support planning and to justify recommended strategies and courses of action.")
NiceSkill.create(acronym: "S0186", description: "Skill in applying crisis planning procedures.")
NiceSkill.create(acronym: "S0187", description: "Skill in applying various analytical methods, tools, and techniques (e.g., competing hypotheses; chain of reasoning; scenario methods; denial and deception detection; high impact-low probability; network/association or link analysis; Bayesian, Delphi, and Pattern analyses).")
NiceSkill.create(acronym: "S0188", description: "Skill in assessing a target's frame of reference (e.g., motivation, technical capability, organizational structure, sensitivities).")
NiceSkill.create(acronym: "S0189", description: "Skill in assessing and/or estimating effects generated during and after cyber operations.")
NiceSkill.create(acronym: "S0190", description: "Skill in assessing current tools to identify needed improvements.")
NiceSkill.create(acronym: "S0191", description: "Skill in assessing the applicability of available analytical tools to various situations.")
NiceSkill.create(acronym: "S0192", description: "Skill in auditing firewalls, perimeters, routers, and intrusion detection systems.")
NiceSkill.create(acronym: "S0193", description: "Skill in complying with the legal restrictions for targeted information.")
NiceSkill.create(acronym: "S0194", description: "Skill in conducting non-attributable research.")
NiceSkill.create(acronym: "S0195", description: "Skill in conducting research using all available sources.")
NiceSkill.create(acronym: "S0196", description: "Skill in conducting research using deep web.")
NiceSkill.create(acronym: "S0197", description: "Skill in conducting social network analysis, buddy list analysis, and/or cookie analysis.")
NiceSkill.create(acronym: "S0198", description: "Skill in conducting social network analysis.")
NiceSkill.create(acronym: "S0199", description: "Skill in creating and extracting important information from packet captures.")
NiceSkill.create(acronym: "S0200", description: "Skill in creating collection requirements in support of data acquisition activities.")
NiceSkill.create(acronym: "S0201", description: "Skill in creating plans in support of remote operations. (i.e., hot/warm/cold/alternative sites, disaster recovery).")
NiceSkill.create(acronym: "S0202", description: "Skill in data mining techniques (e.g., searching file systems) and analysis.")
NiceSkill.create(acronym: "S0203", description: "Skill in defining and characterizing all pertinent aspects of the operational environment.")
NiceSkill.create(acronym: "S0204", description: "Skill in depicting source or collateral data on a network map.")
NiceSkill.create(acronym: "S0205", description: "Skill in determining appropriate targeting options through the evaluation of available capabilities against desired effects.")
NiceSkill.create(acronym: "S0206", description: "Skill in determining installed patches on various operating systems and identifying patch signatures.")
NiceSkill.create(acronym: "S0207", description: "Skill in determining the effect of various router and firewall configurations on traffic patterns and network performance in both LAN and WAN environments.")
NiceSkill.create(acronym: "S0208", description: "Skill in determining the physical location of network devices.")
NiceSkill.create(acronym: "S0209", description: "Skill in developing and executing comprehensive cyber operations assessment programs for assessing and validating operational performance characteristics.")
NiceSkill.create(acronym: "S0210", description: "Skill in developing intelligence reports.")
NiceSkill.create(acronym: "S0211", description: "Skill in developing or recommending analytic approaches or solutions to problems and situations for which information is incomplete or for which no precedent exists.")
NiceSkill.create(acronym: "S0212", description: "Skill in disseminating items of highest intelligence value in a timely manner.")
NiceSkill.create(acronym: "S0213", description: "Skill in documenting and communicating complex technical and programmatic information.")
NiceSkill.create(acronym: "S0214", description: "Skill in evaluating accesses for intelligence value.")
NiceSkill.create(acronym: "S0215", description: "Skill in evaluating and interpreting metadata.")
NiceSkill.create(acronym: "S0216", description: "Skill in evaluating available capabilities against desired effects to provide effective courses of action.")
NiceSkill.create(acronym: "S0217", description: "Skill in evaluating data sources for relevance, reliability, and objectivity.")
NiceSkill.create(acronym: "S0218", description: "Skill in evaluating information for reliability, validity, and relevance.")
NiceSkill.create(acronym: "S0219", description: "Skill in evaluating information to recognize relevance, priority, etc.")
NiceSkill.create(acronym: "S0220", description: "Skill in exploiting/querying organizational and/or partner collection databases.")
NiceSkill.create(acronym: "S0221", description: "Skill in extracting information from packet captures.")
NiceSkill.create(acronym: "S0222", description: "Skill in fusion analysis ")
NiceSkill.create(acronym: "S0223", description: "Skill in generating operation plans in support of mission and target requirements.")
NiceSkill.create(acronym: "S0224", description: "Skill in gisting target communications.")
NiceSkill.create(acronym: "S0225", description: "Skill in identifying a target’s communications networks.")
NiceSkill.create(acronym: "S0226", description: "Skill in identifying a target's network characteristics. ")
NiceSkill.create(acronym: "S0227", description: "Skill in identifying alternative analytical interpretations to minimize unanticipated outcomes.")
NiceSkill.create(acronym: "S0228", description: "Skill in identifying critical target elements, to include critical target elements for the cyber domain.")
NiceSkill.create(acronym: "S0229", description: "Skill in identifying cyber threats which may jeopardize organization and/or partner interests.")
NiceSkill.create(acronym: "S0230", description: "WITHDRAWN: Integrated into S0066")
NiceSkill.create(acronym: "S0231", description: "Skill in identifying how a target communicates.")
NiceSkill.create(acronym: "S0232", description: "Skill in identifying intelligence gaps and limitations.")
NiceSkill.create(acronym: "S0233", description: "Skill in identifying language issues that may have an impact on organization objectives.")
NiceSkill.create(acronym: "S0234", description: "Skill in identifying leads for target development.")
NiceSkill.create(acronym: "S0235", description: "Skill in identifying non-target regional languages and dialects")
NiceSkill.create(acronym: "S0236", description: "Skill in identifying the devices that work at each level of protocol models.")
NiceSkill.create(acronym: "S0237", description: "Skill in identifying, locating, and tracking targets via geospatial analysis techniques")
NiceSkill.create(acronym: "S0238", description: "Skill in information prioritization as it relates to operations.")
NiceSkill.create(acronym: "S0239", description: "Skill in interpreting compiled and interpretive programming languages.")
NiceSkill.create(acronym: "S0240", description: "Skill in interpreting metadata and content as applied by collection systems.")
NiceSkill.create(acronym: "S0241", description: "Skill in interpreting traceroute results, as they apply to network analysis and reconstruction. ")
NiceSkill.create(acronym: "S0242", description: "Skill in interpreting vulnerability scanner results to identify vulnerabilities.")
NiceSkill.create(acronym: "S0243", description: "Skill in knowledge management, including technical documentation techniques (e.g., Wiki page).")
NiceSkill.create(acronym: "S0244", description: "Skill in managing client relationships, including determining client needs/requirements, managing client expectations, and demonstrating commitment to delivering quality results.")
NiceSkill.create(acronym: "S0245", description: "Skill in navigating network visualization software.")
NiceSkill.create(acronym: "S0246", description: "Skill in number normalization.")
NiceSkill.create(acronym: "S0247", description: "Skill in performing data fusion from existing intelligence for enabling new and continued collection.")
NiceSkill.create(acronym: "S0248", description: "Skill in performing target system analysis.")
NiceSkill.create(acronym: "S0249", description: "Skill in preparing and presenting briefings.")
NiceSkill.create(acronym: "S0250", description: "Skill in preparing plans and related correspondence.")
NiceSkill.create(acronym: "S0251", description: "Skill in prioritizing target language material.")
NiceSkill.create(acronym: "S0252", description: "Skill in processing collected data for follow-on analysis.")
NiceSkill.create(acronym: "S0253", description: "Skill in providing analysis on target-related matters (e.g., language, cultural, communications).")
NiceSkill.create(acronym: "S0254", description: "Skill in providing analysis to aid writing phased after action reports.")
NiceSkill.create(acronym: "S0255", description: "Skill in providing real-time, actionable geolocation information utilizing target infrastructures.")
NiceSkill.create(acronym: "S0256", description: "Skill in providing understanding of target or threat systems through the identification and link analysis of physical, functional, or behavioral relationships.")
NiceSkill.create(acronym: "S0257", description: "Skill in reading, interpreting, writing, modifying, and executing simple scripts (e.g., PERL, VBS) on Windows and Unix systems (e.g., those that perform tasks like parsing large data files, automating manual tasks, and fetching/processing remote data).")
NiceSkill.create(acronym: "S0258", description: "Skill in recognizing and interpreting malicious network activity in traffic.")
NiceSkill.create(acronym: "S0259", description: "Skill in recognizing denial and deception techniques of the target.")
NiceSkill.create(acronym: "S0260", description: "Skill in recognizing midpoint opportunities and essential information.")
NiceSkill.create(acronym: "S0261", description: "Skill in recognizing relevance of information.")
NiceSkill.create(acronym: "S0262", description: "Skill in recognizing significant changes in a target’s communication patterns.")
NiceSkill.create(acronym: "S0263", description: "Skill in recognizing technical information that may be used for leads for metadata analysis.")
NiceSkill.create(acronym: "S0264", description: "Skill in recognizing technical information that may be used for leads to enable remote operations (data includes users, passwords, email addresses, IP ranges of the target, frequency in DNI behavior, mail servers, domain servers, SMTP header information).")
NiceSkill.create(acronym: "S0265", description: "Skill in recognizing technical information that may be used for target development including intelligence development. ")
NiceSkill.create(acronym: "S0266", description: "Skill in relevant programming languages (e.g., C++, Python, etc.). ")
NiceSkill.create(acronym: "S0267", description: "Skill in remote command line and Graphic User Interface (GUI) tool usage.")
NiceSkill.create(acronym: "S0268", description: "Skill in researching essential information.")
NiceSkill.create(acronym: "S0269", description: "Skill in researching vulnerabilities and exploits utilized in traffic.")
NiceSkill.create(acronym: "S0270", description: "Skill in reverse engineering (e.g., hex editing, binary packaging utilities, debugging, and strings analysis) to identify function and ownership of remote tools.")
NiceSkill.create(acronym: "S0271", description: "Skill in reviewing and editing assessment products.")
NiceSkill.create(acronym: "S0272", description: "Skill in reviewing and editing intelligence products from various sources for cyber operations.")
NiceSkill.create(acronym: "S0273", description: "Skill in reviewing and editing plans.")
NiceSkill.create(acronym: "S0274", description: "Skill in reviewing and editing target materials.")
NiceSkill.create(acronym: "S0275", description: "Skill in server administration.")
NiceSkill.create(acronym: "S0276", description: "Skill in survey, collection, and analysis of wireless LAN metadata.")
NiceSkill.create(acronym: "S0277", description: "Skill in synthesizing, analyzing, and prioritizing meaning across data sets.")
NiceSkill.create(acronym: "S0278", description: "Skill in tailoring analysis to the necessary levels (e.g., classification and organizational).")
NiceSkill.create(acronym: "S0279", description: "Skill in target development in direct support of collection operations.")
NiceSkill.create(acronym: "S0280", description: "Skill in target network anomaly identification (e.g., intrusions, dataflow or processing, target implementation of new technologies).")
NiceSkill.create(acronym: "S0281", description: "Skill in technical writing.")
NiceSkill.create(acronym: "S0282", description: "Skill in testing and evaluating tools for implementation.")
NiceSkill.create(acronym: "S0283", description: "Skill in transcribing target language communications.")
NiceSkill.create(acronym: "S0284", description: "Skill in translating target graphic and/or voice language materials.")
NiceSkill.create(acronym: "S0285", description: "Skill in using Boolean operators to construct simple and complex queries.")
NiceSkill.create(acronym: "S0286", description: "Skill in using databases to identify target-relevant information.")
NiceSkill.create(acronym: "S0287", description: "Skill in using geospatial data and applying geospatial resources.")
NiceSkill.create(acronym: "S0288", description: "Skill in using multiple analytic tools, databases, and techniques (e.g., Analyst’s Notebook, A-Space, Anchory, M3, divergent/convergent thinking, link charts, matrices, etc.).")
NiceSkill.create(acronym: "S0289", description: "Skill in using multiple search engines (e.g., Google, Yahoo, LexisNexis, DataStar) and tools in conducting open-source searches.")
NiceSkill.create(acronym: "S0290", description: "Skill in using non-attributable networks.")
NiceSkill.create(acronym: "S0291", description: "Skill in using research methods including multiple, different sources to reconstruct a target network.")
NiceSkill.create(acronym: "S0292", description: "Skill in using targeting databases and software packages.")
NiceSkill.create(acronym: "S0293", description: "Skill in using tools, techniques, and procedures to remotely exploit and establish persistence on a target.")
NiceSkill.create(acronym: "S0294", description: "Skill in using trace route tools and interpreting the results as they apply to network analysis and reconstruction.")
NiceSkill.create(acronym: "S0295", description: "Skill in using various open source data collection tools (online trade, DNS, mail, etc.).")
NiceSkill.create(acronym: "S0296", description: "Skill in utilizing feedback to improve processes, products, and services.")
NiceSkill.create(acronym: "S0297", description: "Skill in utilizing virtual collaborative workspaces and/or tools (e.g., IWS, VTCs, chat rooms, SharePoint).")
NiceSkill.create(acronym: "S0298", description: "Skill in verifying the integrity of all files. (e.g., checksums, Exclusive OR, secure hashes, check constraints, etc.).")
NiceSkill.create(acronym: "S0299", description: "Skill in wireless network target analysis, templating, and geolocation.")
NiceSkill.create(acronym: "S0300", description: "Skill in writing (and submitting) requirements to meet gaps in technical capabilities.")
NiceSkill.create(acronym: "S0301", description: "Skill in writing about facts and ideas in a clear, convincing, and organized manner.")
NiceSkill.create(acronym: "S0302", description: "Skill in writing effectiveness reports.")
NiceSkill.create(acronym: "S0303", description: "Skill in writing, reviewing and editing cyber-related Intelligence/assessment products from multiple sources.")
NiceSkill.create(acronym: "S0304", description: "Skill to access information on current assets available, usage.")
NiceSkill.create(acronym: "S0305", description: "Skill to access the databases where plans/directives/guidance are maintained.")
NiceSkill.create(acronym: "S0306", description: "Skill to analyze strategic guidance for issues requiring clarification and/or additional guidance.")
NiceSkill.create(acronym: "S0307", description: "Skill to analyze target or threat sources of strength and morale.")
NiceSkill.create(acronym: "S0308", description: "Skill to anticipate intelligence capability employment requirements.")
NiceSkill.create(acronym: "S0309", description: "Skill to anticipate key target or threat activities which are likely to prompt a leadership decision.")
NiceSkill.create(acronym: "S0310", description: "Skill to apply analytical standards to evaluate intelligence products.")
NiceSkill.create(acronym: "S0311", description: "Skill to apply the capabilities, limitations and tasking methodologies of available platforms, sensors, architectures and apparatus as they apply to organization objectives.")
NiceSkill.create(acronym: "S0312", description: "Skill to apply the process used to assess the performance and impact of cyber operations.")
NiceSkill.create(acronym: "S0313", description: "Skill to articulate a needs statement/requirement and integrate new and emerging collection capabilities, accesses and/or processes into collection operations.")
NiceSkill.create(acronym: "S0314", description: "Skill to articulate intelligence capabilities available to support execution of the plan.")
NiceSkill.create(acronym: "S0315", description: "Skill to articulate the needs of joint planners to all-source analysts.")
NiceSkill.create(acronym: "S0316", description: "Skill to associate Intelligence gaps to priority information requirements and observables.")
NiceSkill.create(acronym: "S0317", description: "Skill to compare indicators/observables with requirements.")
NiceSkill.create(acronym: "S0318", description: "Skill to conceptualize the entirety of the intelligence process in the multiple domains and dimensions.")
NiceSkill.create(acronym: "S0319", description: "Skill to convert intelligence requirements into intelligence production tasks.")
NiceSkill.create(acronym: "S0320", description: "Skill to coordinate the development of tailored intelligence products.")
NiceSkill.create(acronym: "S0321", description: "Skill to correlate intelligence priorities to the allocation of intelligence resources/assets.")
NiceSkill.create(acronym: "S0322", description: "Skill to craft indicators of operational progress/success.")
NiceSkill.create(acronym: "S0323", description: "Skill to create and maintain up-to-date planning documents and tracking of services/production.")
NiceSkill.create(acronym: "S0324", description: "Skill to determine feasibility of collection.")
NiceSkill.create(acronym: "S0325", description: "Skill to develop a collection plan that clearly shows the discipline that can be used to collect the information needed.")
NiceSkill.create(acronym: "S0326", description: "Skill to distinguish between notional and actual resources and their applicability to the plan under development.")
NiceSkill.create(acronym: "S0327", description: "Skill to ensure that the collection strategy leverages all available resources. ")
NiceSkill.create(acronym: "S0328", description: "Skill to evaluate factors of the operational environment to objectives, and information requirements.")
NiceSkill.create(acronym: "S0329", description: "Skill to evaluate requests for information to determine if response information exists.")
NiceSkill.create(acronym: "S0330", description: "Skill to evaluate the capabilities, limitations and tasking methodologies of organic, theater, national, coalition and other collection capabilities. ")
NiceSkill.create(acronym: "S0331", description: "Skill to express orally and in writing the relationship between intelligence capability limitations and decision-making risk and impacts on the overall operation.")
NiceSkill.create(acronym: "S0332", description: "Skill to extract information from available tools and applications associated with collection requirements and collection operations management.")
NiceSkill.create(acronym: "S0333", description: "Skill to graphically depict decision support materials containing intelligence and partner capability estimates.")
NiceSkill.create(acronym: "S0334", description: "Skill to identify and apply tasking, collection, processing, exploitation and dissemination to associated collection disciplines. ")
NiceSkill.create(acronym: "S0335", description: "Skill to identify Intelligence gaps.")
NiceSkill.create(acronym: "S0336", description: "Skill to identify when priority information requirements are satisfied.")
NiceSkill.create(acronym: "S0337", description: "Skill to implement established procedures for evaluating collection management and operations activities.")
NiceSkill.create(acronym: "S0338", description: "Skill to interpret planning guidance to discern level of analytical support required.")
NiceSkill.create(acronym: "S0339", description: "Skill to interpret readiness reporting, its operational relevance and intelligence collection impact.")
NiceSkill.create(acronym: "S0340", description: "Skill to monitor target or threat situation and environmental factors.")
NiceSkill.create(acronym: "S0341", description: "Skill to monitor threat effects to partner capabilities and maintain a running estimate.")
NiceSkill.create(acronym: "S0342", description: "Skill to optimize collection system performance through repeated adjustment, testing, and re-adjustment.")
NiceSkill.create(acronym: "S0343", description: "Skill to orchestrate intelligence planning teams, coordinate collection and production support, and monitor status.")
NiceSkill.create(acronym: "S0344", description: "Skill to prepare and deliver reports, presentations and briefings, to include using visual aids or presentation technology.")
NiceSkill.create(acronym: "S0345", description: "Skill to relate intelligence resources/assets to anticipated intelligence requirements.")
NiceSkill.create(acronym: "S0346", description: "Skill to resolve conflicting collection requirements.")
NiceSkill.create(acronym: "S0347", description: "Skill to review performance specifications and historical information about collection assets.")
NiceSkill.create(acronym: "S0348", description: "Skill to specify collections and/or taskings that must be conducted in the near term.")
NiceSkill.create(acronym: "S0349", description: "Skill to synchronize operational assessment procedures with the critical information requirement process.")
NiceSkill.create(acronym: "S0350", description: "Skill to synchronize planning activities and required intelligence support.")
NiceSkill.create(acronym: "S0351", description: "Skill to translate the capabilities, limitations and tasking methodologies of organic, theater, national, coalition and other collection capabilities.")
NiceSkill.create(acronym: "S0352", description: "Skill to use collaborative tools and environments for collection operations.")
NiceSkill.create(acronym: "S0353", description: "Skill to use systems and/or tools to track collection requirements and determine if they are satisfied.")
NiceSkill.create(acronym: "S0354", description: "Skill in creating policies that reflect the business’s core privacy objectives.")
NiceSkill.create(acronym: "S0355", description: "Skill in negotiating vendor agreements and evaluating vendor privacy practices.")
NiceSkill.create(acronym: "S0356", description: "Skill in communicating with all levels of management including Board members (e.g., interpersonal skills, approachability, effective listening skills, appropriate use of style and language for the audience). ")
NiceSkill.create(acronym: "S0357", description: "Skill to anticipate new security threats.")
NiceSkill.create(acronym: "S0358", description: "Skill to remain aware of evolving technical infrastructures.")
NiceSkill.create(acronym: "S0359", description: "Skill to use critical thinking to analyze organizational patterns and relationships.")
NiceSkill.create(acronym: "S0360", description: "Skill to analyze and assess internal and external partner cyber operations capabilities and tools.")
NiceSkill.create(acronym: "S0361", description: "Skill to analyze and assess internal and external partner intelligence processes and the development of information requirements and essential information.")
NiceSkill.create(acronym: "S0362", description: "Skill to analyze and assess internal and external partner organization capabilities and limitations (those with tasking, collection, processing, exploitation and dissemination responsibilities).")
NiceSkill.create(acronym: "S0363", description: "Skill to analyze and assess internal and external partner reporting.")
NiceSkill.create(acronym: "S0364", description: "Skill to develop insights about the context of an organization’s threat environment")
NiceSkill.create(acronym: "S0365", description: "Skill to design incident response for cloud service models.")
NiceSkill.create(acronym: "S0366", description: "Skill to identify successful capabilities to find solutions to less common and more complex system problems.")
NiceSkill.create(acronym: "S0367", description: "Skill to apply cybersecurity and privacy principles to organizational requirements (relevant to confidentiality, integrity, availability, authentication, non-repudiation).")
NiceSkill.create(acronym: "S0368", description: "Skill to use risk scoring to inform performance-based and cost-effective approaches to help organizations to identify, assess, and manage cybersecurity risk.")
NiceSkill.create(acronym: "S0369", description: "Skill to identify sources, characteristics, and uses of the organization’s data assets.")
NiceSkill.create(acronym: "S0370", description: "Skill to use cyber defense Service Provider reporting structure and processes within one’s own organization.")
NiceSkill.create(acronym: "S0371", description: "Skill to respond and take local actions in response to threat sharing alerts from service providers.")
NiceSkill.create(acronym: "S0372", description: "Skill to translate, track, and prioritize information needs and intelligence collection requirements across the extended enterprise.")
NiceSkill.create(acronym: "S0373", description: "Skill to ensure that accountability information is collected for information system and information and communications technology supply chain infrastructure components.")
NiceSkill.create(acronym: "S0374",	description: "Skill to identify cybersecurity and privacy issues that stem from connections with internal and external customers and partner organizations.")

puts "Created #{NiceSkill.count} NICE skills."