NiceAbility.destroy_all

NiceAbility.create(acronym: "A0001", description: "Ability to identify systemic security issues based on the analysis of vulnerability and configuration data.")
NiceAbility.create(acronym: "A0002", description: "Ability to match the appropriate knowledge repository technology for a given application or environment.")
NiceAbility.create(acronym: "A0003", description: "Ability to determine the validity of technology trend data.")
NiceAbility.create(acronym: "A0004", description: "Ability to develop curriculum that speaks to the topic at the appropriate level for the target audience.")
NiceAbility.create(acronym: "A0005", description: "Ability to decrypt digital data collections.")
NiceAbility.create(acronym: "A0006", description: "Ability to prepare and deliver education and awareness briefings to ensure that systems, network, and data users are aware of and adhere to systems security policies and procedures.")
NiceAbility.create(acronym: "A0007", description: "Ability to tailor code analysis for application-specific concerns.")
NiceAbility.create(acronym: "A0008", description: "Ability to apply the methods, standards, and approaches for describing, analyzing, and documenting an organization's enterprise information technology (IT) architecture (e.g., Open Group Architecture Framework [TOGAF], Department of Defense Architecture Framework [DoDAF], Federal Enterprise Architecture Framework [FEAF]).")
NiceAbility.create(acronym: "A0009", description: "Ability to apply supply chain risk management standards.")
NiceAbility.create(acronym: "A0010", description: "Ability to analyze malware.")
NiceAbility.create(acronym: "A0011", description: "Ability to answer questions in a clear and concise manner.")
NiceAbility.create(acronym: "A0012", description: "Ability to ask clarifying questions.")
NiceAbility.create(acronym: "A0013", description: "Ability to communicate complex information, concepts, or ideas in a confident and well-organized manner through verbal, written, and/or visual means. ")
NiceAbility.create(acronym: "A0014", description: "Ability to communicate effectively when writing.")
NiceAbility.create(acronym: "A0015", description: "Ability to conduct vulnerability scans and recognize vulnerabilities in security systems.")
NiceAbility.create(acronym: "A0016", description: "Ability to facilitate small group discussions.")
NiceAbility.create(acronym: "A0017", description: "Ability to gauge learner understanding and knowledge level.")
NiceAbility.create(acronym: "A0018", description: "Ability to prepare and present briefings.")
NiceAbility.create(acronym: "A0019", description: "Ability to produce technical documentation.")
NiceAbility.create(acronym: "A0020", description: "Ability to provide effective feedback to students for improving learning.")
NiceAbility.create(acronym: "A0021", description: "Ability to use and understand complex mathematical concepts (e.g., discrete math).")
NiceAbility.create(acronym: "A0022", description: "Ability to apply principles of adult learning.")
NiceAbility.create(acronym: "A0023", description: "Ability to design valid and reliable assessments.")
NiceAbility.create(acronym: "A0024", description: "Ability to develop clear directions and instructional materials.")
NiceAbility.create(acronym: "A0025", description: "Ability to accurately define incidents, problems, and events in the trouble ticketing system.")
NiceAbility.create(acronym: "A0026", description: "Ability to analyze test data.")
NiceAbility.create(acronym: "A0027", description: "Ability to apply an organization's goals and objectives to develop and maintain architecture.")
NiceAbility.create(acronym: "A0028", description: "Ability to assess and forecast manpower requirements to meet organizational objectives.")
NiceAbility.create(acronym: "A0029", description: "Ability to build complex data structures and high-level programming languages.")
NiceAbility.create(acronym: "A0030", description: "Ability to collect, verify, and validate test data.")
NiceAbility.create(acronym: "A0031", description: "Ability to conduct and implement market research to understand government and industry capabilities and appropriate pricing.")
NiceAbility.create(acronym: "A0032", description: "Ability to develop curriculum for use within a virtual environment.")
NiceAbility.create(acronym: "A0033", description: "Ability to develop policy, plans, and strategy in compliance with laws, regulations, policies, and standards in support of organizational cyber activities.")
NiceAbility.create(acronym: "A0034", description: "Ability to develop, update, and/or maintain standard operating procedures (SOPs).")
NiceAbility.create(acronym: "A0035", description: "Ability to dissect a problem and examine the interrelationships between data that may appear unrelated.")
NiceAbility.create(acronym: "A0036", description: "Ability to identify basic common coding flaws at a high level.")
NiceAbility.create(acronym: "A0037", description: "Ability to leverage best practices and lessons learned of external organizations and academic institutions dealing with cyber issues.")
NiceAbility.create(acronym: "A0038", description: "Ability to optimize systems to meet enterprise performance requirements.")
NiceAbility.create(acronym: "A0039", description: "Ability to oversee the development and update of the life cycle cost estimate.")
NiceAbility.create(acronym: "A0040", description: "Ability to translate data and test results into evaluative conclusions.")
NiceAbility.create(acronym: "A0041", description: "Ability to use data visualization tools (e.g., Flare, HighCharts, AmCharts, D3.js, Processing, Google Visualization API, Tableau, Raphael.js).")
NiceAbility.create(acronym: "A0042", description: "Ability to develop career path opportunities.")
NiceAbility.create(acronym: "A0043", description: "Ability to conduct forensic analyses in and for both Windows and Unix/Linux environments.")
NiceAbility.create(acronym: "A0044", description: "Ability to apply programming language structures (e.g., source code review) and logic.")
NiceAbility.create(acronym: "A0045", description: "Ability to evaluate/ensure the trustworthiness of the supplier and/or product.")
NiceAbility.create(acronym: "A0046", description: "Ability to monitor and assess the potential impact of emerging technologies on laws, regulations, and/or policies.")
NiceAbility.create(acronym: "A0047", description: "Ability to develop secure software according to secure software deployment methodologies, tools, and practices.")
NiceAbility.create(acronym: "A0048", description: "Ability to apply network security architecture concepts including topology, protocols, components, and principles (e.g., application of defense-in-depth).")
NiceAbility.create(acronym: "A0049", description: "Ability to apply secure system design tools, methods and techniques.")
NiceAbility.create(acronym: "A0050", description: "Ability to apply system design tools, methods, and techniques, including automated systems analysis and design tools.")
NiceAbility.create(acronym: "A0051", description: "Ability to execute technology integration processes.")
NiceAbility.create(acronym: "A0052", description: "Ability to operate network equipment including hubs, routers, switches, bridges, servers, transmission media, and related hardware.")
NiceAbility.create(acronym: "A0053", description: "Ability to determine the validity of workforce trend data.")
NiceAbility.create(acronym: "A0054", description: "Ability to apply the Instructional System Design (ISD) methodology.")
NiceAbility.create(acronym: "A0055", description: "Ability to operate common network tools (e.g., ping, traceroute, nslookup).")
NiceAbility.create(acronym: "A0056", description: "Ability to ensure security practices are followed throughout the acquisition process.")
NiceAbility.create(acronym: "A0057", description: "Ability to tailor curriculum that speaks to the topic at the appropriate level for the target audience.")
NiceAbility.create(acronym: "A0058", description: "Ability to execute OS command line (e.g., ipconfig, netstat, dir, nbtstat).")
NiceAbility.create(acronym: "A0059", description: "Ability to operate the organization's LAN/WAN pathways.")
NiceAbility.create(acronym: "A0060", description: "Ability to build architectures and frameworks.")
NiceAbility.create(acronym: "A0061", description: "Ability to design architectures and frameworks.")
NiceAbility.create(acronym: "A0062", description: "Ability to monitor measures or indicators of system performance and availability.")
NiceAbility.create(acronym: "A0063", description: "Ability to operate different electronic communication systems and methods (e.g., e-mail, VOIP, IM, web forums, Direct Video Broadcasts).")
NiceAbility.create(acronym: "A0064", description: "Ability to interpret and translate customer requirements into operational capabilities. ")
NiceAbility.create(acronym: "A0065", description: "Ability to monitor traffic flows across the network.")
NiceAbility.create(acronym: "A0066", description: "Ability to accurately and completely source all data used in intelligence, assessment and/or planning products.")
NiceAbility.create(acronym: "A0067", description: "Ability to adjust to and operate in a diverse, unpredictable, challenging, and fast-paced work environment.")
NiceAbility.create(acronym: "A0068", description: "Ability to apply approved planning development and staffing processes.")
NiceAbility.create(acronym: "A0069", description: "Ability to apply collaborative skills and strategies.")
NiceAbility.create(acronym: "A0070", description: "Ability to apply critical reading/thinking skills.")
NiceAbility.create(acronym: "A0071", description: "Ability to apply language and cultural expertise to analysis.")
NiceAbility.create(acronym: "A0072", description: "Ability to clearly articulate intelligence requirements into well-formulated research questions and data tracking variables for inquiry tracking purposes.")
NiceAbility.create(acronym: "A0073", description: "Ability to clearly articulate intelligence requirements into well-formulated research questions and requests for information.")
NiceAbility.create(acronym: "A0074", description: "Ability to collaborate effectively with others.")
NiceAbility.create(acronym: "A0075", description: "WITHDRAWN: Ability to communicate complex information, concepts, or ideas in a confident and well-organized manner through verbal, written, and/or visual means.")
NiceAbility.create(acronym: "A0076", description: "Ability to coordinate and collaborate with analysts regarding surveillance requirements and essential information development.")
NiceAbility.create(acronym: "A0077", description: "Ability to coordinate cyber operations with other organization functions or support activities.")
NiceAbility.create(acronym: "A0078", description: "Ability to coordinate, collaborate and disseminate information to subordinate, lateral and higher-level organizations.")
NiceAbility.create(acronym: "A0079", description: "Ability to correctly employ each organization or element into the collection plan and matrix.")
NiceAbility.create(acronym: "A0080", description: "Ability to develop or recommend analytic approaches or solutions to problems and situations for which information is incomplete or for which no precedent exists.")
NiceAbility.create(acronym: "A0081", description: "Ability to develop or recommend planning solutions to problems and situations for which no precedent exists.")
NiceAbility.create(acronym: "A0082", description: "Ability to effectively collaborate via virtual teams.")
NiceAbility.create(acronym: "A0083", description: "Ability to evaluate information for reliability, validity, and relevance.")
NiceAbility.create(acronym: "A0084", description: "Ability to evaluate, analyze, and synthesize large quantities of data (which may be fragmented and contradictory) into high quality, fused targeting/intelligence products.")
NiceAbility.create(acronym: "A0085", description: "Ability to exercise judgment when policies are not well-defined.")
NiceAbility.create(acronym: "A0086", description: "Ability to expand network access by conducting target analysis and collection to identify targets of interest.")
NiceAbility.create(acronym: "A0087", description: "Ability to focus research efforts to meet the customer’s decision-making needs.")
NiceAbility.create(acronym: "A0088", description: "Ability to function effectively in a dynamic, fast-paced environment.")
NiceAbility.create(acronym: "A0089", description: "Ability to function in a collaborative environment, seeking continuous consultation with other analysts and experts—both internal and external to the organization—to leverage analytical and technical expertise.")
NiceAbility.create(acronym: "A0090", description: "Ability to identify external partners with common cyber operations interests.")
NiceAbility.create(acronym: "A0091", description: "Ability to identify intelligence gaps.")
NiceAbility.create(acronym: "A0092", description: "Ability to identify/describe target vulnerability.")
NiceAbility.create(acronym: "A0093", description: "Ability to identify/describe techniques/methods for conducting technical exploitation of the target.")
NiceAbility.create(acronym: "A0094", description: "Ability to interpret and apply laws, regulations, policies, and guidance relevant to organization cyber objectives.")
NiceAbility.create(acronym: "A0095", description: "Ability to interpret and translate customer requirements into operational action.")
NiceAbility.create(acronym: "A0096", description: "Ability to interpret and understand complex and rapidly evolving concepts.")
NiceAbility.create(acronym: "A0097", description: "Ability to monitor system operations and react to events in response to triggers and/or observation of trends or unusual activity. ")
NiceAbility.create(acronym: "A0098", description: "Ability to participate as a member of planning teams, coordination groups, and task forces as necessary.")
NiceAbility.create(acronym: "A0099", description: "Ability to perform network collection tactics, techniques, and procedures to include decryption capabilities/tools.")
NiceAbility.create(acronym: "A0100", description: "Ability to perform wireless collection procedures to include decryption capabilities/tools.")
NiceAbility.create(acronym: "A0101", description: "Ability to recognize and mitigate cognitive biases which may affect analysis.")
NiceAbility.create(acronym: "A0102", description: "Ability to recognize and mitigate deception in reporting and analysis.")
NiceAbility.create(acronym: "A0103", description: "Ability to review processed target language materials for accuracy and completeness.")
NiceAbility.create(acronym: "A0104", description: "Ability to select the appropriate implant to achieve operational goals.")
NiceAbility.create(acronym: "A0105", description: "Ability to tailor technical and planning information to a customer’s level of understanding.")
NiceAbility.create(acronym: "A0106", description: "Ability to think critically.")
NiceAbility.create(acronym: "A0107", description: "Ability to think like threat actors.")
NiceAbility.create(acronym: "A0108", description: "Ability to understand objectives and effects.")
NiceAbility.create(acronym: "A0109", description: "Ability to utilize multiple intelligence sources across all intelligence disciplines.")
NiceAbility.create(acronym: "A0110", description: "Ability to monitor advancements in information privacy laws to ensure organizational adaptation and compliance.")
NiceAbility.create(acronym: "A0111", description: "Ability to work across departments and business units to implement organization’s privacy principles and programs, and align privacy objectives with security objectives. ")
NiceAbility.create(acronym: "A0112", description: "Ability to monitor advancements in information privacy technologies to ensure organizational adaptation and compliance.")
NiceAbility.create(acronym: "A0113", description: "Ability to determine whether a security incident violates a privacy principle or legal standard requiring specific legal action.")
NiceAbility.create(acronym: "A0114", description: "Ability to develop or procure curriculum that speaks to the topic at the appropriate level for the target.")
NiceAbility.create(acronym: "A0115", description: "Ability to work across departments and business units to implement organization’s privacy principles and programs, and align privacy objectives with security objectives.")
NiceAbility.create(acronym: "A0116", description: "Ability to prioritize and allocate cybersecurity resources correctly and efficiently.")
NiceAbility.create(acronym: "A0117", description: "Ability to relate strategy, business, and technology in the context of organizational dynamics.")
NiceAbility.create(acronym: "A0118", description: "Ability to understand technology, management, and leadership issues related to organization processes and problem solving.")
NiceAbility.create(acronym: "A0119", description: "Ability to understand the basic concepts and issues related to cyber and its organizational impact.")
NiceAbility.create(acronym: "A0120", description: "Ability to share meaningful insights about the context of an organization’s threat environment that improve its risk management posture.")
NiceAbility.create(acronym: "A0121", description: "Ability to design incident response for cloud service models.")
NiceAbility.create(acronym: "A0122", description: "Ability to design capabilities to find solutions to less common and more complex system problems.")
NiceAbility.create(acronym: "A0123", description: "Ability to apply cybersecurity and privacy principles to organizational requirements (relevant to confidentiality, integrity, availability, authentication, non-repudiation).")
NiceAbility.create(acronym: "A0124", description: "Ability to establish and maintain automated security control assessments")
NiceAbility.create(acronym: "A0125", description: "Ability to author a privacy disclosure statement based on current laws.")
NiceAbility.create(acronym: "A0126", description: "Ability to track the location and configuration of networked devices and software across departments, locations, facilities and, potentially, supporting business functions.")
NiceAbility.create(acronym: "A0127", description: "Ability to deploy continuous monitoring technologies and tools.")
NiceAbility.create(acronym: "A0128", description: "Ability to apply techniques for detecting host and network-based intrusions using intrusion detection technologies.")
NiceAbility.create(acronym: "A0129", description: "Ability to ensure information security management processes are integrated with strategic and operational planning processes.")
NiceAbility.create(acronym: "A0130", description: "Ability to ensure that senior officials within the organization provide information security for the information and systems that support the operations and assets under their control.")
NiceAbility.create(acronym: "A0131", description: "Ability to ensure the organization has adequately trained personnel to assist in complying with security requirements in legislation, Executive Orders, policies, directives, instructions, standards, and guidelines.")
NiceAbility.create(acronym: "A0132", description: "Ability to coordinate with senior leadership of an organization to provide a comprehensive, organization-wide, holistic approach for addressing risk—an approach that provides a greater understanding of the integrated operations of the organization.")
NiceAbility.create(acronym: "A0133", description: "Ability to coordinate with senior leadership of an organization to develop a risk management strategy for the organization providing a strategic view of security-related risks for the organization.")
NiceAbility.create(acronym: "A0134", description: "Ability to coordinate with senior leadership of an organization to facilitate the sharing of risk-related information among authorizing officials and other senior leaders within the organization.")
NiceAbility.create(acronym: "A0135", description: "Ability to coordinate with senior leadership of an organization to provide oversight for all risk management-related activities across the organization to help ensure consistent and effective risk acceptance decisions.")
NiceAbility.create(acronym: "A0136", description: "Ability to coordinate with senior leadership of an organization to ensure that authorization decisions consider all factors necessary for mission and business success.")
NiceAbility.create(acronym: "A0137", description: "Ability to coordinate with senior leadership of an organization to provide an organization-wide forum to consider all sources of risk (including aggregated risk) to organizational operations and assets, individuals, other organizations, and the Nation.")
NiceAbility.create(acronym: "A0138", description: "Ability to coordinate with senior leadership of an organization to promote cooperation and collaboration among authorizing officials to include authorization actions requiring shared responsibility.")
NiceAbility.create(acronym: "A0139", description: "Ability to coordinate with senior leadership of an organization to ensure that the shared responsibility for supporting organizational mission/business functions using external providers of systems, services, and applications receives the needed visibility and is elevated to the appropriate decision-making authorities.")
NiceAbility.create(acronym: "A0140", description: "Ability to coordinate with senior leadership of an organization to identify the organizational risk posture based on the aggregated risk from the operation and use of the systems for which the organization is responsible.")
NiceAbility.create(acronym: "A0141", description: "Ability to work closely with authorizing officials and their designated representatives to help ensure that an organization-wide security program is effectively implemented resulting in adequate security for all organizational systems and environments of operation.")
NiceAbility.create(acronym: "A0142", description: "Ability to work closely with authorizing officials and their designated representatives to help ensure that security considerations are integrated into programming/planning/budgeting cycles, enterprise architectures, and acquisition/system development life cycles.")
NiceAbility.create(acronym: "A0143", description: "Ability to work closely with authorizing officials and their designated representatives to help ensure that organizational systems and common controls are covered by approved security plans and possess current authorizations.")
NiceAbility.create(acronym: "A0144", description: "Ability to work closely with authorizing officials and their designated representatives to help ensure that security-related activities required across the organization are accomplished in an efficient, cost-effective, and timely manner.")
NiceAbility.create(acronym: "A0145", description: "Ability to work closely with authorizing officials and their designated representatives to help ensure that there is centralized reporting of security-related activities.")
NiceAbility.create(acronym: "A0146", description: "Ability to establish the rules for appropriate use and protection of the information and retains that responsibility even when the information is shared with or provided to other organizations.")
NiceAbility.create(acronym: "A0147", description: "Ability to approve security plans, memorandums of agreement or understanding, plans of action and milestones, and determine whether significant changes in the systems or environments of operation require reauthorization.")
NiceAbility.create(acronym: "A0148", description: "Ability to serve as the primary liaison between the enterprise architect and the systems security engineer and coordinates with system owners, common control providers, and system security officers on the allocation of security controls as system-specific, hybrid, or common controls.")
NiceAbility.create(acronym: "A0149", description: "Ability, in close coordination with system security officers, advise authorizing officials, chief information officers, senior information security officers, and the senior accountable official for risk management/risk executive (function), on a range of security-related issues (e.g. establishing system boundaries; assessing the severity of weaknesses and deficiencies in the system; plans of action and milestones; risk mitigation approaches; security alerts; and potential adverse effects of identified vulnerabilities).")
NiceAbility.create(acronym: "A0150", description: "Ability to conduct systems security engineering activities (NIST SP 800-16).")
NiceAbility.create(acronym: "A0151", description: "Ability to capture and refine security requirements and ensure that the requirements are effectively integrated into the component products and systems through purposeful security architecting, design, development, and configuration.")
NiceAbility.create(acronym: "A0152", description: "Ability to employ best practices when implementing security controls within a system including software engineering methodologies; system and security engineering principles; secure design, secure architecture, and secure coding techniques.")
NiceAbility.create(acronym: "A0153", description: "Ability to coordinate their security-related activities with security architects, senior information security officers, system owners, common control providers, and system security officers.")
NiceAbility.create(acronym: "A0154", description: "Ability to conduct a comprehensive assessment of the management, operational, and technical security controls and control enhancements employed within or inherited by a system to determine the effectiveness of the controls (i.e., the extent to which the security controls are implemented correctly, operating as intended, and producing the desired outcome with respect to meeting the security requirements for the system).")
NiceAbility.create(acronym: "A0155", description: "Ability to provide an assessment of the severity of weaknesses or deficiencies discovered in the system and its environment of operation and recommend corrective actions to address identified vulnerabilities.")
NiceAbility.create(acronym: "A0156", description: "Ability to prepare the final security assessment report containing the results and findings from the assessment.")
NiceAbility.create(acronym: "A0157", description: "Ability to assesses a security plan to help ensure that the plan provides a set of security controls for the system that meet the stated security requirements.")
NiceAbility.create(acronym: "A0158", description: "Ability to ensure that functional and security requirements are appropriately addressed in a contract and that the contractor meets the functional and security requirements as stated in the contract.")
NiceAbility.create(acronym: "A0159", description: "Ability to interpret the information collected by network tools (e.g. Nslookup, Ping, and Traceroute).")
NiceAbility.create(acronym: "A0160", description: "Ability to translate, track, and prioritize information needs and intelligence collection requirements across the extended enterprise.")
NiceAbility.create(acronym: "A0161", description: "Ability to integrate information security requirements into the acquisition process; using applicable baseline security controls as one of the sources for security requirements; ensuring a robust software quality control process; and establishing multiple sources (e.g., delivery routes, for critical system elements).")
NiceAbility.create(acronym: "A0162", description: "Ability to ensure information system security, acquisition personnel, legal counsel, and other appropriate advisors and stakeholders are participating in decision making from system concept definition/review and are involved in, or approve of, each milestone decision through the entire system life cycle for systems.")
NiceAbility.create(acronym: "A0177", description: "Ability to recognize the unique aspects of the Communications Security (COMSEC) environment and hierarchy.")
NiceAbility.create(acronym: "A0163", description: "Ability to interpret Communications Security (COMSEC) terminology, guidelines and procedures.")
NiceAbility.create(acronym: "A0164", description: "Ability to identify the roles and responsibilities for appointed Communications Security (COMSEC) personnel.")
NiceAbility.create(acronym: "A0165", description: "Ability to manage Communications Security (COMSEC) material accounting, control and use procedure.")
NiceAbility.create(acronym: "A0166", description: "Ability to identify types of Communications Security (COMSEC) Incidents and how they’re reported.")
NiceAbility.create(acronym: "A0167", description: "Ability to recognize the importance of auditing Communications Security (COMSEC) material and accounts.")
NiceAbility.create(acronym: "A0168", description: "Ability to Identify the requirements of In-Process accounting for Communications Security (COMSEC).")
NiceAbility.create(acronym: "A0170", description: "Ability to identify critical infrastructure systems with information communication technology that were designed without system security considerations.")
NiceAbility.create(acronym: "A0171", description: "Ability to conduct training and education needs assessment.")
NiceAbility.create(acronym: "A0172", description: "Ability to set up a physical or logical sub-networks that separates an internal local area network (LAN) from other untrusted networks.")
NiceAbility.create(acronym: "A0173", description: "Ability to recognize that changes to systems or environment can change residual risks in relation to risk appetite.")
NiceAbility.create(acronym: "A0174", description: "Ability to find and navigate the dark web using the TOR network to locate markets and forums.")
NiceAbility.create(acronym: "A0175", description: "Ability to examine digital media on multiple operating system platforms.")
NiceAbility.create(acronym: "A0176", description: "Ability to maintain databases. (i.e., backup, restore, delete data, transaction log files, etc.).")

puts "Created #{NiceAbility.count} NICE abilities."