services:
  db:
    image: postgres:latest
    volumes:
      - performatron-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=performatron_development
      - POSTGRES_USER=performatron
      - POSTGRES_PASSWORD=password
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/performatron:cached
      - performatron-bundle:/performatron/vendor/bundle
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.
    network_mode: service:db # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=performatron_development
      - BUNDLE_PATH=/performatron/vendor/bundle
      - POSTGRES_USER=performatron
      - POSTGRES_PASSWORD=password

volumes:
  performatron-db:
    external: true
  performatron-bundle:
    external: true